//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWebMobile.NewsTravelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsTravelService.ITravelService")]
    public interface ITravelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/TravelList", ReplyAction="http://tempuri.org/ITravelService/TravelListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour> TravelList(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/TravelList", ReplyAction="http://tempuri.org/ITravelService/TravelListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour>> TravelListAsync(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/GetTravelReadInfo", ReplyAction="http://tempuri.org/ITravelService/GetTravelReadInfoResponse")]
        Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour GetTravelReadInfo(string articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/GetTravelReadInfo", ReplyAction="http://tempuri.org/ITravelService/GetTravelReadInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour> GetTravelReadInfoAsync(string articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/GetArticleLikeitHanatour", ReplyAction="http://tempuri.org/ITravelService/GetArticleLikeitHanatourResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NTB_ARTICLE_LIKEIT_HANATOUR GetArticleLikeitHanatour(string articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/GetArticleLikeitHanatour", ReplyAction="http://tempuri.org/ITravelService/GetArticleLikeitHanatourResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NTB_ARTICLE_LIKEIT_HANATOUR> GetArticleLikeitHanatourAsync(string articleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/SetArticleLikeitHanatour", ReplyAction="http://tempuri.org/ITravelService/SetArticleLikeitHanatourResponse")]
        void SetArticleLikeitHanatour(string articleId, string likeitGubun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/SetArticleLikeitHanatour", ReplyAction="http://tempuri.org/ITravelService/SetArticleLikeitHanatourResponse")]
        System.Threading.Tasks.Task SetArticleLikeitHanatourAsync(string articleId, string likeitGubun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/GetTravelPrevNext", ReplyAction="http://tempuri.org/ITravelService/GetTravelPrevNextResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_PREV_NEXT_SELECT_Result> GetTravelPrevNext(string articleId, Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelService/GetTravelPrevNext", ReplyAction="http://tempuri.org/ITravelService/GetTravelPrevNextResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_PREV_NEXT_SELECT_Result>> GetTravelPrevNextAsync(string articleId, Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITravelServiceChannel : Wow.Tv.FrontWebMobile.NewsTravelService.ITravelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.NewsTravelService.ITravelService>, Wow.Tv.FrontWebMobile.NewsTravelService.ITravelService {
        
        public TravelServiceClient() {
        }
        
        public TravelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TravelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour> TravelList(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition) {
            return base.Channel.TravelList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour>> TravelListAsync(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition) {
            return base.Channel.TravelListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour GetTravelReadInfo(string articleId) {
            return base.Channel.GetTravelReadInfo(articleId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.ArticleClass_Hanatour> GetTravelReadInfoAsync(string articleId) {
            return base.Channel.GetTravelReadInfoAsync(articleId);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NTB_ARTICLE_LIKEIT_HANATOUR GetArticleLikeitHanatour(string articleId) {
            return base.Channel.GetArticleLikeitHanatour(articleId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NTB_ARTICLE_LIKEIT_HANATOUR> GetArticleLikeitHanatourAsync(string articleId) {
            return base.Channel.GetArticleLikeitHanatourAsync(articleId);
        }
        
        public void SetArticleLikeitHanatour(string articleId, string likeitGubun) {
            base.Channel.SetArticleLikeitHanatour(articleId, likeitGubun);
        }
        
        public System.Threading.Tasks.Task SetArticleLikeitHanatourAsync(string articleId, string likeitGubun) {
            return base.Channel.SetArticleLikeitHanatourAsync(articleId, likeitGubun);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_PREV_NEXT_SELECT_Result> GetTravelPrevNext(string articleId, Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition) {
            return base.Channel.GetTravelPrevNext(articleId, condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_PREV_NEXT_SELECT_Result>> GetTravelPrevNextAsync(string articleId, Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition) {
            return base.Channel.GetTravelPrevNextAsync(articleId, condition);
        }
    }
}
