//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.NewsStandService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsStandService.INewsStandService")]
    public interface INewsStandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsStandService/GetNewsStandHeadLine", ReplyAction="http://tempuri.org/INewsStandService/GetNewsStandHeadLineResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.usp_newsStandMetaXMLTopImg_Result> GetNewsStandHeadLine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsStandService/GetNewsStandHeadLine", ReplyAction="http://tempuri.org/INewsStandService/GetNewsStandHeadLineResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.usp_newsStandMetaXMLTopImg_Result>> GetNewsStandHeadLineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsStandService/GetNewsStandHotKeyword", ReplyAction="http://tempuri.org/INewsStandService/GetNewsStandHotKeywordResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWSSTAND_KEWORD_SELECT_Result> GetNewsStandHotKeyword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsStandService/GetNewsStandHotKeyword", ReplyAction="http://tempuri.org/INewsStandService/GetNewsStandHotKeywordResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWSSTAND_KEWORD_SELECT_Result>> GetNewsStandHotKeywordAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsStandServiceChannel : Wow.Tv.FrontWeb.NewsStandService.INewsStandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsStandServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.NewsStandService.INewsStandService>, Wow.Tv.FrontWeb.NewsStandService.INewsStandService {
        
        public NewsStandServiceClient() {
        }
        
        public NewsStandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsStandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsStandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsStandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.usp_newsStandMetaXMLTopImg_Result> GetNewsStandHeadLine() {
            return base.Channel.GetNewsStandHeadLine();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.usp_newsStandMetaXMLTopImg_Result>> GetNewsStandHeadLineAsync() {
            return base.Channel.GetNewsStandHeadLineAsync();
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWSSTAND_KEWORD_SELECT_Result> GetNewsStandHotKeyword() {
            return base.Channel.GetNewsStandHotKeyword();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWSSTAND_KEWORD_SELECT_Result>> GetNewsStandHotKeywordAsync() {
            return base.Channel.GetNewsStandHotKeywordAsync();
        }
    }
}
