//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWebMobile.TvPlayerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveTvInfoModel", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.Broad")]
    [System.SerializableAttribute()]
    public partial class LiveTvInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DayOfTheWeekListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PartnerNameListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanBroadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DayOfTheWeekList {
            get {
                return this.DayOfTheWeekListField;
            }
            set {
                if ((object.ReferenceEquals(this.DayOfTheWeekListField, value) != true)) {
                    this.DayOfTheWeekListField = value;
                    this.RaisePropertyChanged("DayOfTheWeekList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartnerNameList {
            get {
                return this.PartnerNameListField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerNameListField, value) != true)) {
                    this.PartnerNameListField = value;
                    this.RaisePropertyChanged("PartnerNameList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlanBroad {
            get {
                return this.PlanBroadField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanBroadField, value) != true)) {
                    this.PlanBroadField = value;
                    this.RaisePropertyChanged("PlanBroad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramId {
            get {
                return this.ProgramIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramIdField, value) != true)) {
                    this.ProgramIdField = value;
                    this.RaisePropertyChanged("ProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvReplayInfoModel", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.Broad")]
    [System.SerializableAttribute()]
    public partial class TvReplayInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BroadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PartnerNameListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramGubunCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BroadDate {
            get {
                return this.BroadDateField;
            }
            set {
                if ((this.BroadDateField.Equals(value) != true)) {
                    this.BroadDateField = value;
                    this.RaisePropertyChanged("BroadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartnerNameList {
            get {
                return this.PartnerNameListField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerNameListField, value) != true)) {
                    this.PartnerNameListField = value;
                    this.RaisePropertyChanged("PartnerNameList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Point {
            get {
                return this.PointField;
            }
            set {
                if ((this.PointField.Equals(value) != true)) {
                    this.PointField = value;
                    this.RaisePropertyChanged("Point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramGubunCode {
            get {
                return this.ProgramGubunCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramGubunCodeField, value) != true)) {
                    this.ProgramGubunCodeField = value;
                    this.RaisePropertyChanged("ProgramGubunCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramId {
            get {
                return this.ProgramIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramIdField, value) != true)) {
                    this.ProgramIdField = value;
                    this.RaisePropertyChanged("ProgramId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VodInfoModel", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.Broad")]
    [System.SerializableAttribute()]
    public partial class VodInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TvPlayerService.ITvPlayerService")]
    public interface ITvPlayerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvPlayerService/LiveTvInfo", ReplyAction="http://tempuri.org/ITvPlayerService/LiveTvInfoResponse")]
        Wow.Tv.FrontWebMobile.TvPlayerService.LiveTvInfoModel LiveTvInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvPlayerService/LiveTvInfo", ReplyAction="http://tempuri.org/ITvPlayerService/LiveTvInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.FrontWebMobile.TvPlayerService.LiveTvInfoModel> LiveTvInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvPlayerService/TvReplayInfo", ReplyAction="http://tempuri.org/ITvPlayerService/TvReplayInfoResponse")]
        Wow.Tv.FrontWebMobile.TvPlayerService.TvReplayInfoModel TvReplayInfo(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvPlayerService/TvReplayInfo", ReplyAction="http://tempuri.org/ITvPlayerService/TvReplayInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.FrontWebMobile.TvPlayerService.TvReplayInfoModel> TvReplayInfoAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvPlayerService/VodInfo", ReplyAction="http://tempuri.org/ITvPlayerService/VodInfoResponse")]
        Wow.Tv.FrontWebMobile.TvPlayerService.VodInfoModel VodInfo(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvPlayerService/VodInfo", ReplyAction="http://tempuri.org/ITvPlayerService/VodInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.FrontWebMobile.TvPlayerService.VodInfoModel> VodInfoAsync(int num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITvPlayerServiceChannel : Wow.Tv.FrontWebMobile.TvPlayerService.ITvPlayerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TvPlayerServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.TvPlayerService.ITvPlayerService>, Wow.Tv.FrontWebMobile.TvPlayerService.ITvPlayerService {
        
        public TvPlayerServiceClient() {
        }
        
        public TvPlayerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TvPlayerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TvPlayerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TvPlayerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.FrontWebMobile.TvPlayerService.LiveTvInfoModel LiveTvInfo() {
            return base.Channel.LiveTvInfo();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.FrontWebMobile.TvPlayerService.LiveTvInfoModel> LiveTvInfoAsync() {
            return base.Channel.LiveTvInfoAsync();
        }
        
        public Wow.Tv.FrontWebMobile.TvPlayerService.TvReplayInfoModel TvReplayInfo(int num) {
            return base.Channel.TvReplayInfo(num);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.FrontWebMobile.TvPlayerService.TvReplayInfoModel> TvReplayInfoAsync(int num) {
            return base.Channel.TvReplayInfoAsync(num);
        }
        
        public Wow.Tv.FrontWebMobile.TvPlayerService.VodInfoModel VodInfo(int num) {
            return base.Channel.VodInfo(num);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.FrontWebMobile.TvPlayerService.VodInfoModel> VodInfoAsync(int num) {
            return base.Channel.VodInfoAsync(num);
        }
    }
}
