//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.LandService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LandService.ILandService")]
    public interface ILandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILandService/GetMapAddress", ReplyAction="http://tempuri.org/ILandService/GetMapAddressResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NTB_POST GetMapAddress(string Sido, string Gugun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILandService/GetMapAddress", ReplyAction="http://tempuri.org/ILandService/GetMapAddressResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NTB_POST> GetMapAddressAsync(string Sido, string Gugun);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILandServiceChannel : Wow.Tv.FrontWeb.LandService.ILandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LandServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.LandService.ILandService>, Wow.Tv.FrontWeb.LandService.ILandService {
        
        public LandServiceClient() {
        }
        
        public LandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NTB_POST GetMapAddress(string Sido, string Gugun) {
            return base.Channel.GetMapAddress(Sido, Gugun);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NTB_POST> GetMapAddressAsync(string Sido, string Gugun) {
            return base.Channel.GetMapAddressAsync(Sido, Gugun);
        }
    }
}
