//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.MenuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuService.IMenuService")]
    public interface IMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/SearchList", ReplyAction="http://tempuri.org/IMenuService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/SearchList", ReplyAction="http://tempuri.org/IMenuService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/SearchListMenuGroup", ReplyAction="http://tempuri.org/IMenuService/SearchListMenuGroupResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuGroupItem> SearchListMenuGroup(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/SearchListMenuGroup", ReplyAction="http://tempuri.org/IMenuService/SearchListMenuGroupResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuGroupItem>> SearchListMenuGroupAsync(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAt", ReplyAction="http://tempuri.org/IMenuService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetAt(int menuSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAt", ReplyAction="http://tempuri.org/IMenuService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetAtAsync(int menuSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/Save", ReplyAction="http://tempuri.org/IMenuService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/Save", ReplyAction="http://tempuri.org/IMenuService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/Delete", ReplyAction="http://tempuri.org/IMenuService/DeleteResponse")]
        void Delete(int menuSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/Delete", ReplyAction="http://tempuri.org/IMenuService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int menuSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpDown", ReplyAction="http://tempuri.org/IMenuService/UpDownResponse")]
        void UpDown(int menuSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpDown", ReplyAction="http://tempuri.org/IMenuService/UpDownResponse")]
        System.Threading.Tasks.Task UpDownAsync(int menuSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAtByUrl", ReplyAction="http://tempuri.org/IMenuService/GetAtByUrlResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetAtByUrl(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAtByUrl", ReplyAction="http://tempuri.org/IMenuService/GetAtByUrlResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetAtByUrlAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAtByName", ReplyAction="http://tempuri.org/IMenuService/GetAtByNameResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetAtByName(string channelCode, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetAtByName", ReplyAction="http://tempuri.org/IMenuService/GetAtByNameResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetAtByNameAsync(string channelCode, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AuthListSave", ReplyAction="http://tempuri.org/IMenuService/AuthListSaveResponse")]
        void AuthListSave(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuItem[] list, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AuthListSave", ReplyAction="http://tempuri.org/IMenuService/AuthListSaveResponse")]
        System.Threading.Tasks.Task AuthListSaveAsync(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuItem[] list, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AuthSave", ReplyAction="http://tempuri.org/IMenuService/AuthSaveResponse")]
        void AuthSave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AuthSave", ReplyAction="http://tempuri.org/IMenuService/AuthSaveResponse")]
        System.Threading.Tasks.Task AuthSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuList", ReplyAction="http://tempuri.org/IMenuService/GetMenuListResponse")]
        System.Collections.Generic.Dictionary<string, System.Nullable<int>> GetMenuList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/GetMenuList", ReplyAction="http://tempuri.org/IMenuService/GetMenuListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.Nullable<int>>> GetMenuListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuServiceChannel : Wow.Tv.FrontWeb.MenuService.IMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.MenuService.IMenuService>, Wow.Tv.FrontWeb.MenuService.IMenuService {
        
        public MenuServiceClient() {
        }
        
        public MenuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuGroupItem> SearchListMenuGroup(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition) {
            return base.Channel.SearchListMenuGroup(groupSeq, condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuGroupItem>> SearchListMenuGroupAsync(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuCondition condition) {
            return base.Channel.SearchListMenuGroupAsync(groupSeq, condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetAt(int menuSeq) {
            return base.Channel.GetAt(menuSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetAtAsync(int menuSeq) {
            return base.Channel.GetAtAsync(menuSeq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int menuSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Delete(menuSeq, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int menuSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteAsync(menuSeq, loginUser);
        }
        
        public void UpDown(int menuSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.UpDown(menuSeq, isUp, loginUser);
        }
        
        public System.Threading.Tasks.Task UpDownAsync(int menuSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.UpDownAsync(menuSeq, isUp, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetAtByUrl(string url) {
            return base.Channel.GetAtByUrl(url);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetAtByUrlAsync(string url) {
            return base.Channel.GetAtByUrlAsync(url);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetAtByName(string channelCode, string name) {
            return base.Channel.GetAtByName(channelCode, name);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetAtByNameAsync(string channelCode, string name) {
            return base.Channel.GetAtByNameAsync(channelCode, name);
        }
        
        public void AuthListSave(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuItem[] list, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.AuthListSave(groupSeq, list, loginUser);
        }
        
        public System.Threading.Tasks.Task AuthListSaveAsync(int groupSeq, Wow.Tv.Middle.Model.Db49.wowtv.Menu.MenuItem[] list, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.AuthListSaveAsync(groupSeq, list, loginUser);
        }
        
        public void AuthSave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.AuthSave(model, loginUser);
        }
        
        public System.Threading.Tasks.Task AuthSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.AuthSaveAsync(model, loginUser);
        }
        
        public System.Collections.Generic.Dictionary<string, System.Nullable<int>> GetMenuList() {
            return base.Channel.GetMenuList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, System.Nullable<int>>> GetMenuListAsync() {
            return base.Channel.GetMenuListAsync();
        }
    }
}
