//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWebMobile.TextAndLinkService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextAndLinkService.ITextAndLinkService")]
    public interface ITextAndLinkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAndLinkService/GetList", ReplyAction="http://tempuri.org/ITextAndLinkService/GetListResponse")]
        Wow.Tv.Middle.Model.Db49.Article.TextAndLink.TxtNLinkModel<Wow.Tv.Middle.Model.Db49.Article.TextAndLink.JOIN_TXTNLINK_CODE> GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAndLinkService/GetList", ReplyAction="http://tempuri.org/ITextAndLinkService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.TextAndLink.TxtNLinkModel<Wow.Tv.Middle.Model.Db49.Article.TextAndLink.JOIN_TXTNLINK_CODE>> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAndLinkService/Save", ReplyAction="http://tempuri.org/ITextAndLinkService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.Article.NTB_TEXT_LINK model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAndLinkService/Save", ReplyAction="http://tempuri.org/ITextAndLinkService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.Article.NTB_TEXT_LINK model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAndLinkService/Delete", ReplyAction="http://tempuri.org/ITextAndLinkService/DeleteResponse")]
        void Delete(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAndLinkService/Delete", ReplyAction="http://tempuri.org/ITextAndLinkService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] deleteList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITextAndLinkServiceChannel : Wow.Tv.FrontWebMobile.TextAndLinkService.ITextAndLinkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextAndLinkServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.TextAndLinkService.ITextAndLinkService>, Wow.Tv.FrontWebMobile.TextAndLinkService.ITextAndLinkService {
        
        public TextAndLinkServiceClient() {
        }
        
        public TextAndLinkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextAndLinkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextAndLinkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextAndLinkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.TextAndLink.TxtNLinkModel<Wow.Tv.Middle.Model.Db49.Article.TextAndLink.JOIN_TXTNLINK_CODE> GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.TextAndLink.TxtNLinkModel<Wow.Tv.Middle.Model.Db49.Article.TextAndLink.JOIN_TXTNLINK_CODE>> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.Article.NTB_TEXT_LINK model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.Article.NTB_TEXT_LINK model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int[] deleteList) {
            base.Channel.Delete(deleteList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] deleteList) {
            return base.Channel.DeleteAsync(deleteList);
        }
    }
}
