//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWebMobile.BoardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BoardService.IBoardService")]
    public interface IBoardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/SearchList", ReplyAction="http://tempuri.org/IBoardService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/SearchList", ReplyAction="http://tempuri.org/IBoardService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/GetAt", ReplyAction="http://tempuri.org/IBoardService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD GetAt(int boardSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/GetAt", ReplyAction="http://tempuri.org/IBoardService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD> GetAtAsync(int boardSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/Save", ReplyAction="http://tempuri.org/IBoardService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/Save", ReplyAction="http://tempuri.org/IBoardService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/Delete", ReplyAction="http://tempuri.org/IBoardService/DeleteResponse")]
        void Delete(int boardSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/Delete", ReplyAction="http://tempuri.org/IBoardService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int boardSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/DeleteList", ReplyAction="http://tempuri.org/IBoardService/DeleteListResponse")]
        void DeleteList(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/DeleteList", ReplyAction="http://tempuri.org/IBoardService/DeleteListResponse")]
        System.Threading.Tasks.Task DeleteListAsync(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/ExcelExport", ReplyAction="http://tempuri.org/IBoardService/ExcelExportResponse")]
        System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBoardService/ExcelExport", ReplyAction="http://tempuri.org/IBoardService/ExcelExportResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBoardServiceChannel : Wow.Tv.FrontWebMobile.BoardService.IBoardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoardServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.BoardService.IBoardService>, Wow.Tv.FrontWebMobile.BoardService.IBoardService {
        
        public BoardServiceClient() {
        }
        
        public BoardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BoardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD GetAt(int boardSeq) {
            return base.Channel.GetAt(boardSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD> GetAtAsync(int boardSeq) {
            return base.Channel.GetAtAsync(boardSeq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int boardSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Delete(boardSeq, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int boardSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteAsync(boardSeq, loginUser);
        }
        
        public void DeleteList(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.DeleteList(seqList, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteListAsync(int[] seqList, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteListAsync(seqList, loginUser);
        }
        
        public System.IO.MemoryStream ExcelExport(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition) {
            return base.Channel.ExcelExport(condition);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> ExcelExportAsync(Wow.Tv.Middle.Model.Db49.wowtv.Board.BoardCondition condition) {
            return base.Channel.ExcelExportAsync(condition);
        }
    }
}
