//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.LectureService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LectureService.ILectureService")]
    public interface ILectureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetList", ReplyAction="http://tempuri.org/ILectureService/GetListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE> GetList(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetList", ReplyAction="http://tempuri.org/ILectureService/GetListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE>> GetListAsync(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetDetail", ReplyAction="http://tempuri.org/ILectureService/GetDetailResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl GetDetail(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetDetail", ReplyAction="http://tempuri.org/ILectureService/GetDetailResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl> GetDetailAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/Save", ReplyAction="http://tempuri.org/ILectureService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl data, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/Save", ReplyAction="http://tempuri.org/ILectureService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl data, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/Delete", ReplyAction="http://tempuri.org/ILectureService/DeleteResponse")]
        void Delete(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/Delete", ReplyAction="http://tempuri.org/ILectureService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int[] deleteList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetCalendarDate", ReplyAction="http://tempuri.org/ILectureService/GetCalendarDateResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_PARTNER[] GetCalendarDate(System.DateTime searchDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetCalendarDate", ReplyAction="http://tempuri.org/ILectureService/GetCalendarDateResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_PARTNER[]> GetCalendarDateAsync(System.DateTime searchDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/SearchSchedule", ReplyAction="http://tempuri.org/ILectureService/SearchScheduleResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.Lecture.DtlSchedule SearchSchedule(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/SearchSchedule", ReplyAction="http://tempuri.org/ILectureService/SearchScheduleResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.Lecture.DtlSchedule> SearchScheduleAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetDateCount", ReplyAction="http://tempuri.org/ILectureService/GetDateCountResponse")]
        System.Collections.Generic.Dictionary<string, int> GetDateCount(string FirstDate, string LastDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetDateCount", ReplyAction="http://tempuri.org/ILectureService/GetDateCountResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetDateCountAsync(string FirstDate, string LastDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/ApplyLecture", ReplyAction="http://tempuri.org/ILectureService/ApplyLectureResponse")]
        bool ApplyLecture(Wow.Tv.Middle.Model.Db49.wownet.TAB_ACADEMY_APPL model, Wow.Tv.Middle.Model.Common.LoginUserInfo loginUserInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/ApplyLecture", ReplyAction="http://tempuri.org/ILectureService/ApplyLectureResponse")]
        System.Threading.Tasks.Task<bool> ApplyLectureAsync(Wow.Tv.Middle.Model.Db49.wownet.TAB_ACADEMY_APPL model, Wow.Tv.Middle.Model.Common.LoginUserInfo loginUserInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetQuickLectures", ReplyAction="http://tempuri.org/ILectureService/GetQuickLecturesResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE> GetQuickLectures(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetQuickLectures", ReplyAction="http://tempuri.org/ILectureService/GetQuickLecturesResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE>> GetQuickLecturesAsync(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetLatestLecture", ReplyAction="http://tempuri.org/ILectureService/GetLatestLectureResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_SCHEDULE> GetLatestLecture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILectureService/GetLatestLecture", ReplyAction="http://tempuri.org/ILectureService/GetLatestLectureResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_SCHEDULE>> GetLatestLectureAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILectureServiceChannel : Wow.Tv.FrontWeb.LectureService.ILectureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LectureServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.LectureService.ILectureService>, Wow.Tv.FrontWeb.LectureService.ILectureService {
        
        public LectureServiceClient() {
        }
        
        public LectureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LectureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LectureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE> GetList(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition) {
            return base.Channel.GetList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE>> GetListAsync(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition) {
            return base.Channel.GetListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl GetDetail(int seq) {
            return base.Channel.GetDetail(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl> GetDetailAsync(int seq) {
            return base.Channel.GetDetailAsync(seq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl data, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(data, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureScheduleDtl data, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(data, loginUser);
        }
        
        public void Delete(int[] deleteList) {
            base.Channel.Delete(deleteList);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int[] deleteList) {
            return base.Channel.DeleteAsync(deleteList);
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_PARTNER[] GetCalendarDate(System.DateTime searchDate) {
            return base.Channel.GetCalendarDate(searchDate);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_PARTNER[]> GetCalendarDateAsync(System.DateTime searchDate) {
            return base.Channel.GetCalendarDateAsync(searchDate);
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.Lecture.DtlSchedule SearchSchedule(int seq) {
            return base.Channel.SearchSchedule(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.Lecture.DtlSchedule> SearchScheduleAsync(int seq) {
            return base.Channel.SearchScheduleAsync(seq);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetDateCount(string FirstDate, string LastDate) {
            return base.Channel.GetDateCount(FirstDate, LastDate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetDateCountAsync(string FirstDate, string LastDate) {
            return base.Channel.GetDateCountAsync(FirstDate, LastDate);
        }
        
        public bool ApplyLecture(Wow.Tv.Middle.Model.Db49.wownet.TAB_ACADEMY_APPL model, Wow.Tv.Middle.Model.Common.LoginUserInfo loginUserInfo) {
            return base.Channel.ApplyLecture(model, loginUserInfo);
        }
        
        public System.Threading.Tasks.Task<bool> ApplyLectureAsync(Wow.Tv.Middle.Model.Db49.wownet.TAB_ACADEMY_APPL model, Wow.Tv.Middle.Model.Common.LoginUserInfo loginUserInfo) {
            return base.Channel.ApplyLectureAsync(model, loginUserInfo);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE> GetQuickLectures(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition) {
            return base.Channel.GetQuickLectures(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES__CODE>> GetQuickLecturesAsync(Wow.Tv.Middle.Model.Db49.wownet.Lecture.LectureCondition condition) {
            return base.Channel.GetQuickLecturesAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_SCHEDULE> GetLatestLecture() {
            return base.Channel.GetLatestLecture();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wownet.Lecture.JOIN_LECTURES_SCHEDULE>> GetLatestLectureAsync() {
            return base.Channel.GetLatestLectureAsync();
        }
    }
}
