//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.CastService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramCastModel", Namespace="http://schemas.datacontract.org/2004/07/Wow.Tv.Middle.Biz.MyProgram")]
    [System.SerializableAttribute()]
    public partial class ProgramCastModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE AttachFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowList ProWowListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Wow.Tv.Middle.Model.Db49.broadcast.NTB_PROGRAM_CAST ProgramCastField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE AttachFile {
            get {
                return this.AttachFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachFileField, value) != true)) {
                    this.AttachFileField = value;
                    this.RaisePropertyChanged("AttachFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowList ProWowList {
            get {
                return this.ProWowListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProWowListField, value) != true)) {
                    this.ProWowListField = value;
                    this.RaisePropertyChanged("ProWowList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Wow.Tv.Middle.Model.Db49.broadcast.NTB_PROGRAM_CAST ProgramCast {
            get {
                return this.ProgramCastField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramCastField, value) != true)) {
                    this.ProgramCastField = value;
                    this.RaisePropertyChanged("ProgramCast");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CastService.ICastService")]
    public interface ICastService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/GetAt", ReplyAction="http://tempuri.org/ICastService/GetAtResponse")]
        Wow.Tv.FrontWeb.CastService.ProgramCastModel GetAt(int payNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/GetAt", ReplyAction="http://tempuri.org/ICastService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.FrontWeb.CastService.ProgramCastModel> GetAtAsync(int payNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/SearchList", ReplyAction="http://tempuri.org/ICastService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.FrontWeb.CastService.ProgramCastModel> SearchList(Wow.Tv.Middle.Model.Db49.broadcast.MyProgram.CastCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/SearchList", ReplyAction="http://tempuri.org/ICastService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.FrontWeb.CastService.ProgramCastModel>> SearchListAsync(Wow.Tv.Middle.Model.Db49.broadcast.MyProgram.CastCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/Save", ReplyAction="http://tempuri.org/ICastService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.broadcast.NTB_PROGRAM_CAST model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/Save", ReplyAction="http://tempuri.org/ICastService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.broadcast.NTB_PROGRAM_CAST model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/Delete", ReplyAction="http://tempuri.org/ICastService/DeleteResponse")]
        void Delete(int programBannerSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/Delete", ReplyAction="http://tempuri.org/ICastService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int programBannerSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/DeleteList", ReplyAction="http://tempuri.org/ICastService/DeleteListResponse")]
        void DeleteList(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICastService/DeleteList", ReplyAction="http://tempuri.org/ICastService/DeleteListResponse")]
        System.Threading.Tasks.Task DeleteListAsync(int[] seqList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICastServiceChannel : Wow.Tv.FrontWeb.CastService.ICastService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CastServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.CastService.ICastService>, Wow.Tv.FrontWeb.CastService.ICastService {
        
        public CastServiceClient() {
        }
        
        public CastServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CastServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CastServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CastServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.FrontWeb.CastService.ProgramCastModel GetAt(int payNo) {
            return base.Channel.GetAt(payNo);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.FrontWeb.CastService.ProgramCastModel> GetAtAsync(int payNo) {
            return base.Channel.GetAtAsync(payNo);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.FrontWeb.CastService.ProgramCastModel> SearchList(Wow.Tv.Middle.Model.Db49.broadcast.MyProgram.CastCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.FrontWeb.CastService.ProgramCastModel>> SearchListAsync(Wow.Tv.Middle.Model.Db49.broadcast.MyProgram.CastCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.broadcast.NTB_PROGRAM_CAST model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, attachFile, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.broadcast.NTB_PROGRAM_CAST model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, attachFile, loginUser);
        }
        
        public void Delete(int programBannerSeq) {
            base.Channel.Delete(programBannerSeq);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int programBannerSeq) {
            return base.Channel.DeleteAsync(programBannerSeq);
        }
        
        public void DeleteList(int[] seqList) {
            base.Channel.DeleteList(seqList);
        }
        
        public System.Threading.Tasks.Task DeleteListAsync(int[] seqList) {
            return base.Channel.DeleteListAsync(seqList);
        }
    }
}
