//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.PilotService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PilotService.IPilotService")]
    public interface IPilotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/SearchList", ReplyAction="http://tempuri.org/IPilotService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Pilot.PilotCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/SearchList", ReplyAction="http://tempuri.org/IPilotService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Pilot.PilotCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/GetAt", ReplyAction="http://tempuri.org/IPilotService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD GetAt(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/GetAt", ReplyAction="http://tempuri.org/IPilotService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD> GetAtAsync(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/Save", ReplyAction="http://tempuri.org/IPilotService/SaveResponse")]
        void Save(Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/Save", ReplyAction="http://tempuri.org/IPilotService/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/Delete", ReplyAction="http://tempuri.org/IPilotService/DeleteResponse")]
        void Delete(int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPilotService/Delete", ReplyAction="http://tempuri.org/IPilotService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int seq);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPilotServiceChannel : Wow.Tv.FrontWeb.PilotService.IPilotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PilotServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.PilotService.IPilotService>, Wow.Tv.FrontWeb.PilotService.IPilotService {
        
        public PilotServiceClient() {
        }
        
        public PilotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PilotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PilotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PilotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.Pilot.PilotCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.Pilot.PilotCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD GetAt(int seq) {
            return base.Channel.GetAt(seq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD> GetAtAsync(int seq) {
            return base.Channel.GetAtAsync(seq);
        }
        
        public void Save(Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD model) {
            base.Channel.Save(model);
        }
        
        public System.Threading.Tasks.Task SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.TAB_BOARD model) {
            return base.Channel.SaveAsync(model);
        }
        
        public void Delete(int seq) {
            base.Channel.Delete(seq);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int seq) {
            return base.Channel.DeleteAsync(seq);
        }
    }
}
