//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWebMobile.BroadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BroadService.IBroadLiveService")]
    public interface IBroadLiveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/GetAtLive", ReplyAction="http://tempuri.org/IBroadLiveService/GetAtLiveResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE GetAtLive(int broadLiveID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/GetAtLive", ReplyAction="http://tempuri.org/IBroadLiveService/GetAtLiveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE> GetAtLiveAsync(int broadLiveID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/SearchListLive", ReplyAction="http://tempuri.org/IBroadLiveService/SearchListLiveResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE> SearchListLive(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadLiveCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/SearchListLive", ReplyAction="http://tempuri.org/IBroadLiveService/SearchListLiveResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE>> SearchListLiveAsync(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadLiveCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/SaveLive", ReplyAction="http://tempuri.org/IBroadLiveService/SaveLiveResponse")]
        int SaveLive(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/SaveLive", ReplyAction="http://tempuri.org/IBroadLiveService/SaveLiveResponse")]
        System.Threading.Tasks.Task<int> SaveLiveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/DeleteLive", ReplyAction="http://tempuri.org/IBroadLiveService/DeleteLiveResponse")]
        void DeleteLive(int broadLiveID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/DeleteLive", ReplyAction="http://tempuri.org/IBroadLiveService/DeleteLiveResponse")]
        System.Threading.Tasks.Task DeleteLiveAsync(int broadLiveID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/DeleteLiveList", ReplyAction="http://tempuri.org/IBroadLiveService/DeleteLiveListResponse")]
        void DeleteLiveList(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBroadLiveService/DeleteLiveList", ReplyAction="http://tempuri.org/IBroadLiveService/DeleteLiveListResponse")]
        System.Threading.Tasks.Task DeleteLiveListAsync(int[] seqList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBroadLiveServiceChannel : Wow.Tv.FrontWebMobile.BroadService.IBroadLiveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BroadLiveServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.BroadService.IBroadLiveService>, Wow.Tv.FrontWebMobile.BroadService.IBroadLiveService {
        
        public BroadLiveServiceClient() {
        }
        
        public BroadLiveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BroadLiveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BroadLiveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BroadLiveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE GetAtLive(int broadLiveID) {
            return base.Channel.GetAtLive(broadLiveID);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE> GetAtLiveAsync(int broadLiveID) {
            return base.Channel.GetAtLiveAsync(broadLiveID);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE> SearchListLive(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadLiveCondition condition) {
            return base.Channel.SearchListLive(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE>> SearchListLiveAsync(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadLiveCondition condition) {
            return base.Channel.SearchListLiveAsync(condition);
        }
        
        public int SaveLive(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveLive(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveLiveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_BROAD_LIVE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveLiveAsync(model, loginUser);
        }
        
        public void DeleteLive(int broadLiveID) {
            base.Channel.DeleteLive(broadLiveID);
        }
        
        public System.Threading.Tasks.Task DeleteLiveAsync(int broadLiveID) {
            return base.Channel.DeleteLiveAsync(broadLiveID);
        }
        
        public void DeleteLiveList(int[] seqList) {
            base.Channel.DeleteLiveList(seqList);
        }
        
        public System.Threading.Tasks.Task DeleteLiveListAsync(int[] seqList) {
            return base.Channel.DeleteLiveListAsync(seqList);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BroadService.INewsProgramService")]
    public interface INewsProgramService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetCategoryList", ReplyAction="http://tempuri.org/INewsProgramService/GetCategoryListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CODE> GetCategoryList(int pseq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetCategoryList", ReplyAction="http://tempuri.org/INewsProgramService/GetCategoryListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CODE>> GetCategoryListAsync(int pseq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAt", ReplyAction="http://tempuri.org/INewsProgramService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG GetAt(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAt", ReplyAction="http://tempuri.org/INewsProgramService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG> GetAtAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAtImgSchedule", ReplyAction="http://tempuri.org/INewsProgramService/GetAtImgScheduleResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE GetAtImgSchedule(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAtImgSchedule", ReplyAction="http://tempuri.org/INewsProgramService/GetAtImgScheduleResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE> GetAtImgScheduleAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMainAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetMainAttachFileResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetMainAttachFile(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMainAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetMainAttachFileResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetMainAttachFileAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetSubAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetSubAttachFileResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetSubAttachFile(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetSubAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetSubAttachFileResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetSubAttachFileAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetRectangleAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetRectangleAttachFileResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetRectangleAttachFile(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetRectangleAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetRectangleAttachFileResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetRectangleAttachFileAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetThumbnailAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetThumbnailAttachFileResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetThumbnailAttachFile(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetThumbnailAttachFile", ReplyAction="http://tempuri.org/INewsProgramService/GetThumbnailAttachFileResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetThumbnailAttachFileAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchList", ReplyAction="http://tempuri.org/INewsProgramService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG> SearchList(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchList", ReplyAction="http://tempuri.org/INewsProgramService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG>> SearchListAsync(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchListImgSchedule", ReplyAction="http://tempuri.org/INewsProgramService/SearchListImgScheduleResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE> SearchListImgSchedule(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchListImgSchedule", ReplyAction="http://tempuri.org/INewsProgramService/SearchListImgScheduleResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE>> SearchListImgScheduleAsync(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SaveSchedule", ReplyAction="http://tempuri.org/INewsProgramService/SaveScheduleResponse")]
        void SaveSchedule(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SaveSchedule", ReplyAction="http://tempuri.org/INewsProgramService/SaveScheduleResponse")]
        System.Threading.Tasks.Task SaveScheduleAsync(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/Save", ReplyAction="http://tempuri.org/INewsProgramService/SaveResponse")]
        void Save(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/Save", ReplyAction="http://tempuri.org/INewsProgramService/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SaveFromMyProgram", ReplyAction="http://tempuri.org/INewsProgramService/SaveFromMyProgramResponse")]
        void SaveFromMyProgram(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SaveFromMyProgram", ReplyAction="http://tempuri.org/INewsProgramService/SaveFromMyProgramResponse")]
        System.Threading.Tasks.Task SaveFromMyProgramAsync(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/ExcelFileSave", ReplyAction="http://tempuri.org/INewsProgramService/ExcelFileSaveResponse")]
        void ExcelFileSave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/ExcelFileSave", ReplyAction="http://tempuri.org/INewsProgramService/ExcelFileSaveResponse")]
        System.Threading.Tasks.Task ExcelFileSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetExcelFile", ReplyAction="http://tempuri.org/INewsProgramService/GetExcelFileResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetExcelFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetExcelFile", ReplyAction="http://tempuri.org/INewsProgramService/GetExcelFileResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetExcelFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/Delete", ReplyAction="http://tempuri.org/INewsProgramService/DeleteResponse")]
        void Delete(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/Delete", ReplyAction="http://tempuri.org/INewsProgramService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteImgSchedule", ReplyAction="http://tempuri.org/INewsProgramService/DeleteImgScheduleResponse")]
        void DeleteImgSchedule(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteImgSchedule", ReplyAction="http://tempuri.org/INewsProgramService/DeleteImgScheduleResponse")]
        System.Threading.Tasks.Task DeleteImgScheduleAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowListPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/GetWowListPartnerListResponse")]
        Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowList[] GetWowListPartnerList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowListPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/GetWowListPartnerListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowList[]> GetWowListPartnerListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetProgramPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/GetProgramPartnerListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_PARTNER[] GetProgramPartnerList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetProgramPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/GetProgramPartnerListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_PARTNER[]> GetProgramPartnerListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/AddProgramPartner", ReplyAction="http://tempuri.org/INewsProgramService/AddProgramPartnerResponse")]
        void AddProgramPartner(string programCode, int payNo, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/AddProgramPartner", ReplyAction="http://tempuri.org/INewsProgramService/AddProgramPartnerResponse")]
        System.Threading.Tasks.Task AddProgramPartnerAsync(string programCode, int payNo, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramPartner", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramPartnerResponse")]
        void DeleteProgramPartner(string programCode, int payNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramPartner", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramPartnerResponse")]
        System.Threading.Tasks.Task DeleteProgramPartnerAsync(string programCode, int payNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramPartnerListResponse")]
        void DeleteProgramPartnerList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramPartnerListResponse")]
        System.Threading.Tasks.Task DeleteProgramPartnerListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetProgramAdminList", ReplyAction="http://tempuri.org/INewsProgramService/GetProgramAdminListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_ADMIN[] GetProgramAdminList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetProgramAdminList", ReplyAction="http://tempuri.org/INewsProgramService/GetProgramAdminListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_ADMIN[]> GetProgramAdminListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/AddProgramAdmin", ReplyAction="http://tempuri.org/INewsProgramService/AddProgramAdminResponse")]
        void AddProgramAdmin(string programCode, int adminSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/AddProgramAdmin", ReplyAction="http://tempuri.org/INewsProgramService/AddProgramAdminResponse")]
        System.Threading.Tasks.Task AddProgramAdminAsync(string programCode, int adminSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramAdmin", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramAdminResponse")]
        void DeleteProgramAdmin(string programCode, int adminSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramAdmin", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramAdminResponse")]
        System.Threading.Tasks.Task DeleteProgramAdminAsync(string programCode, int adminSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramAdminList", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramAdminListResponse")]
        void DeleteProgramAdminList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/DeleteProgramAdminList", ReplyAction="http://tempuri.org/INewsProgramService/DeleteProgramAdminListResponse")]
        System.Threading.Tasks.Task DeleteProgramAdminListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAdminProgram", ReplyAction="http://tempuri.org/INewsProgramService/GetAdminProgramResponse")]
        string[] GetAdminProgram(int adminSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAdminProgram", ReplyAction="http://tempuri.org/INewsProgramService/GetAdminProgramResponse")]
        System.Threading.Tasks.Task<string[]> GetAdminProgramAsync(int adminSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchListRunDown", ReplyAction="http://tempuri.org/INewsProgramService/SearchListRunDownResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN[] SearchListRunDown(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchListRunDown", ReplyAction="http://tempuri.org/INewsProgramService/SearchListRunDownResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN[]> SearchListRunDownAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNowRunDown", ReplyAction="http://tempuri.org/INewsProgramService/GetNowRunDownResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN GetNowRunDown();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNowRunDown", ReplyAction="http://tempuri.org/INewsProgramService/GetNowRunDownResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN> GetNowRunDownAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetListStockVod", ReplyAction="http://tempuri.org/INewsProgramService/GetListStockVodResponse")]
        Wow.Tv.Middle.Model.Db49.editVOD.tblStockClass[] GetListStockVod();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetListStockVod", ReplyAction="http://tempuri.org/INewsProgramService/GetListStockVodResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.editVOD.tblStockClass[]> GetListStockVodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetListMarket", ReplyAction="http://tempuri.org/INewsProgramService/GetListMarketResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NUP_BROAD_MAIN_ARTICLE_SELECT_Result[] GetListMarket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetListMarket", ReplyAction="http://tempuri.org/INewsProgramService/GetListMarketResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_BROAD_MAIN_ARTICLE_SELECT_Result[]> GetListMarketAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/ProgramOrder", ReplyAction="http://tempuri.org/INewsProgramService/ProgramOrderResponse")]
        void ProgramOrder(Wow.Tv.Middle.Model.Db49.wowtv.TAB_PGM_ORDER model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/ProgramOrder", ReplyAction="http://tempuri.org/INewsProgramService/ProgramOrderResponse")]
        System.Threading.Tasks.Task ProgramOrderAsync(Wow.Tv.Middle.Model.Db49.wowtv.TAB_PGM_ORDER model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNotice1", ReplyAction="http://tempuri.org/INewsProgramService/GetNotice1Response")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[] GetNotice1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNotice1", ReplyAction="http://tempuri.org/INewsProgramService/GetNotice1Response")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[]> GetNotice1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNotice2", ReplyAction="http://tempuri.org/INewsProgramService/GetNotice2Response")]
        Wow.Tv.Middle.Model.Db49.wownet.TAB_LECTURES_SCHEDULE[] GetNotice2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNotice2", ReplyAction="http://tempuri.org/INewsProgramService/GetNotice2Response")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.TAB_LECTURES_SCHEDULE[]> GetNotice2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNotice3", ReplyAction="http://tempuri.org/INewsProgramService/GetNotice3Response")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[] GetNotice3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetNotice3", ReplyAction="http://tempuri.org/INewsProgramService/GetNotice3Response")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[]> GetNotice3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/IsHoliDayCheck", ReplyAction="http://tempuri.org/INewsProgramService/IsHoliDayCheckResponse")]
        bool IsHoliDayCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/IsHoliDayCheck", ReplyAction="http://tempuri.org/INewsProgramService/IsHoliDayCheckResponse")]
        System.Threading.Tasks.Task<bool> IsHoliDayCheckAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowNetData", ReplyAction="http://tempuri.org/INewsProgramService/GetWowNetDataResponse")]
        Wow.Tv.Middle.Model.Db49.broadcast.BestStockPro[] GetWowNetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowNetData", ReplyAction="http://tempuri.org/INewsProgramService/GetWowNetDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.BestStockPro[]> GetWowNetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowNetData2", ReplyAction="http://tempuri.org/INewsProgramService/GetWowNetData2Response")]
        Wow.Tv.Middle.Model.Db49.broadcast.USP_GetRecommendPro3_Result[] GetWowNetData2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowNetData2", ReplyAction="http://tempuri.org/INewsProgramService/GetWowNetData2Response")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.USP_GetRecommendPro3_Result[]> GetWowNetData2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowFaData", ReplyAction="http://tempuri.org/INewsProgramService/GetWowFaDataResponse")]
        Wow.Tv.Middle.Model.Db16.wowfa.WOW_M_BANNER[] GetWowFaData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowFaData", ReplyAction="http://tempuri.org/INewsProgramService/GetWowFaDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db16.wowfa.WOW_M_BANNER[]> GetWowFaDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowFaDataLecture", ReplyAction="http://tempuri.org/INewsProgramService/GetWowFaDataLectureResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.NUP_MAIN_COMMON_LECTURE_SELECT_Result[] GetWowFaDataLecture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowFaDataLecture", ReplyAction="http://tempuri.org/INewsProgramService/GetWowFaDataLectureResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.NUP_MAIN_COMMON_LECTURE_SELECT_Result[]> GetWowFaDataLectureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowStarData", ReplyAction="http://tempuri.org/INewsProgramService/GetWowStarDataResponse")]
        Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_video_Result[] GetWowStarData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowStarData", ReplyAction="http://tempuri.org/INewsProgramService/GetWowStarDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_video_Result[]> GetWowStarDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowStarDataStock", ReplyAction="http://tempuri.org/INewsProgramService/GetWowStarDataStockResponse")]
        Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_p2p_wowtv_Result GetWowStarDataStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetWowStarDataStock", ReplyAction="http://tempuri.org/INewsProgramService/GetWowStarDataStockResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_p2p_wowtv_Result> GetWowStarDataStockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetJunMunGaData", ReplyAction="http://tempuri.org/INewsProgramService/GetJunMunGaDataResponse")]
        Wow.Tv.Middle.Model.Db49.broadcast.Pro_wow_junmunga_broadcast GetJunMunGaData(string proId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetJunMunGaData", ReplyAction="http://tempuri.org/INewsProgramService/GetJunMunGaDataResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.Pro_wow_junmunga_broadcast> GetJunMunGaDataAsync(string proId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/TickerList", ReplyAction="http://tempuri.org/INewsProgramService/TickerListResponse")]
        Wow.Tv.Middle.Model.Common.DumyModel[] TickerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/TickerList", ReplyAction="http://tempuri.org/INewsProgramService/TickerListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.DumyModel[]> TickerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetPartnerEventItemPrice", ReplyAction="http://tempuri.org/INewsProgramService/GetPartnerEventItemPriceResponse")]
        int[] GetPartnerEventItemPrice(string proId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetPartnerEventItemPrice", ReplyAction="http://tempuri.org/INewsProgramService/GetPartnerEventItemPriceResponse")]
        System.Threading.Tasks.Task<int[]> GetPartnerEventItemPriceAsync(string proId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetProWowWellList", ReplyAction="http://tempuri.org/INewsProgramService/GetProWowWellListResponse")]
        Wow.Tv.Middle.Model.Db49.broadcast.USP_GetBroadcast1ByWellList_Result[] GetProWowWellList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetProWowWellList", ReplyAction="http://tempuri.org/INewsProgramService/GetProWowWellListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.USP_GetBroadcast1ByWellList_Result[]> GetProWowWellListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetStockKing3", ReplyAction="http://tempuri.org/INewsProgramService/GetStockKing3Response")]
        Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowListStockKing[] GetStockKing3();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetStockKing3", ReplyAction="http://tempuri.org/INewsProgramService/GetStockKing3Response")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowListStockKing[]> GetStockKing3Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/TodayStrategy", ReplyAction="http://tempuri.org/INewsProgramService/TodayStrategyResponse")]
        Wow.Tv.Middle.Model.Db49.wownet.USP_GetTabStrategetApplication_Result[] TodayStrategy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/TodayStrategy", ReplyAction="http://tempuri.org/INewsProgramService/TodayStrategyResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.USP_GetTabStrategetApplication_Result[]> TodayStrategyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetOnAirPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/GetOnAirPartnerListResponse")]
        Wow.Tv.Middle.Model.Db49.broadcast.usp_GetlivePro_Result[] GetOnAirPartnerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetOnAirPartnerList", ReplyAction="http://tempuri.org/INewsProgramService/GetOnAirPartnerListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.usp_GetlivePro_Result[]> GetOnAirPartnerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetCornerVod", ReplyAction="http://tempuri.org/INewsProgramService/GetCornerVodResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.usp_GetCornerVODList_WEB_Result> GetCornerVod(string scCode, int currentIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetCornerVod", ReplyAction="http://tempuri.org/INewsProgramService/GetCornerVodResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.usp_GetCornerVODList_WEB_Result>> GetCornerVodAsync(string scCode, int currentIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetCornerVodAll", ReplyAction="http://tempuri.org/INewsProgramService/GetCornerVodAllResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.NUP_GetCornerVODList_WEB_Result> GetCornerVodAll(int currentIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetCornerVodAll", ReplyAction="http://tempuri.org/INewsProgramService/GetCornerVodAllResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.NUP_GetCornerVODList_WEB_Result>> GetCornerVodAllAsync(int currentIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMenuByProgramCode", ReplyAction="http://tempuri.org/INewsProgramService/GetMenuByProgramCodeResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU[] GetMenuByProgramCode(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMenuByProgramCode", ReplyAction="http://tempuri.org/INewsProgramService/GetMenuByProgramCodeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU[]> GetMenuByProgramCodeAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMenuByCornerSeq", ReplyAction="http://tempuri.org/INewsProgramService/GetMenuByCornerSeqResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetMenuByCornerSeq(string programCode, string scCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMenuByCornerSeq", ReplyAction="http://tempuri.org/INewsProgramService/GetMenuByCornerSeqResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetMenuByCornerSeqAsync(string programCode, string scCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetTrade", ReplyAction="http://tempuri.org/INewsProgramService/GetTradeResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT GetTrade(int boardContentSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetTrade", ReplyAction="http://tempuri.org/INewsProgramService/GetTradeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT> GetTradeAsync(int boardContentSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchListRandom", ReplyAction="http://tempuri.org/INewsProgramService/SearchListRandomResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG> SearchListRandom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/SearchListRandom", ReplyAction="http://tempuri.org/INewsProgramService/SearchListRandomResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG>> SearchListRandomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/Migration", ReplyAction="http://tempuri.org/INewsProgramService/MigrationResponse")]
        void Migration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/Migration", ReplyAction="http://tempuri.org/INewsProgramService/MigrationResponse")]
        System.Threading.Tasks.Task MigrationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMigrationProgramList", ReplyAction="http://tempuri.org/INewsProgramService/GetMigrationProgramListResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[] GetMigrationProgramList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetMigrationProgramList", ReplyAction="http://tempuri.org/INewsProgramService/GetMigrationProgramListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[]> GetMigrationProgramListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/MigrationProgramCornerList", ReplyAction="http://tempuri.org/INewsProgramService/MigrationProgramCornerListResponse")]
        Wow.Tv.Middle.Model.Db49.editVOD.tblSubConerList[] MigrationProgramCornerList(string programCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/MigrationProgramCornerList", ReplyAction="http://tempuri.org/INewsProgramService/MigrationProgramCornerListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.editVOD.tblSubConerList[]> MigrationProgramCornerListAsync(string programCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAllProgramList", ReplyAction="http://tempuri.org/INewsProgramService/GetAllProgramListResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramList_Result[] GetAllProgramList(string programNameStart, string programNameEnd, string year, int startIndex, int endIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAllProgramList", ReplyAction="http://tempuri.org/INewsProgramService/GetAllProgramListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramList_Result[]> GetAllProgramListAsync(string programNameStart, string programNameEnd, string year, int startIndex, int endIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAllProgramEtcList", ReplyAction="http://tempuri.org/INewsProgramService/GetAllProgramEtcListResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramEtcList_Result[] GetAllProgramEtcList(string year, int startIndex, int endIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsProgramService/GetAllProgramEtcList", ReplyAction="http://tempuri.org/INewsProgramService/GetAllProgramEtcListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramEtcList_Result[]> GetAllProgramEtcListAsync(string year, int startIndex, int endIndex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsProgramServiceChannel : Wow.Tv.FrontWebMobile.BroadService.INewsProgramService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsProgramServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.BroadService.INewsProgramService>, Wow.Tv.FrontWebMobile.BroadService.INewsProgramService {
        
        public NewsProgramServiceClient() {
        }
        
        public NewsProgramServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsProgramServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsProgramServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsProgramServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CODE> GetCategoryList(int pseq) {
            return base.Channel.GetCategoryList(pseq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.TAB_CODE>> GetCategoryListAsync(int pseq) {
            return base.Channel.GetCategoryListAsync(pseq);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG GetAt(string programCode) {
            return base.Channel.GetAt(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG> GetAtAsync(string programCode) {
            return base.Channel.GetAtAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE GetAtImgSchedule(string programCode) {
            return base.Channel.GetAtImgSchedule(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE> GetAtImgScheduleAsync(string programCode) {
            return base.Channel.GetAtImgScheduleAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetMainAttachFile(string programCode) {
            return base.Channel.GetMainAttachFile(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetMainAttachFileAsync(string programCode) {
            return base.Channel.GetMainAttachFileAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetSubAttachFile(string programCode) {
            return base.Channel.GetSubAttachFile(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetSubAttachFileAsync(string programCode) {
            return base.Channel.GetSubAttachFileAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetRectangleAttachFile(string programCode) {
            return base.Channel.GetRectangleAttachFile(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetRectangleAttachFileAsync(string programCode) {
            return base.Channel.GetRectangleAttachFileAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetThumbnailAttachFile(string programCode) {
            return base.Channel.GetThumbnailAttachFile(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetThumbnailAttachFileAsync(string programCode) {
            return base.Channel.GetThumbnailAttachFileAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG> SearchList(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG>> SearchListAsync(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE> SearchListImgSchedule(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition) {
            return base.Channel.SearchListImgSchedule(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.IMG_SCHEDULE>> SearchListImgScheduleAsync(Wow.Tv.Middle.Model.Db90.DNRS.NewsProgram.NewsProgramCondition condition) {
            return base.Channel.SearchListImgScheduleAsync(condition);
        }
        
        public void SaveSchedule(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model) {
            base.Channel.SaveSchedule(model);
        }
        
        public System.Threading.Tasks.Task SaveScheduleAsync(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model) {
            return base.Channel.SaveScheduleAsync(model);
        }
        
        public void Save(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile) {
            base.Channel.Save(model, mainAttachFile, subAttachFile, rectangleAttachFile, thumbnailAttachFile);
        }
        
        public System.Threading.Tasks.Task SaveAsync(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile) {
            return base.Channel.SaveAsync(model, mainAttachFile, subAttachFile, rectangleAttachFile, thumbnailAttachFile);
        }
        
        public void SaveFromMyProgram(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile) {
            base.Channel.SaveFromMyProgram(model, mainAttachFile, subAttachFile, rectangleAttachFile, thumbnailAttachFile);
        }
        
        public System.Threading.Tasks.Task SaveFromMyProgramAsync(Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE mainAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE subAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE rectangleAttachFile, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE thumbnailAttachFile) {
            return base.Channel.SaveFromMyProgramAsync(model, mainAttachFile, subAttachFile, rectangleAttachFile, thumbnailAttachFile);
        }
        
        public void ExcelFileSave(Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE model) {
            base.Channel.ExcelFileSave(model);
        }
        
        public System.Threading.Tasks.Task ExcelFileSaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE model) {
            return base.Channel.ExcelFileSaveAsync(model);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE GetExcelFile() {
            return base.Channel.GetExcelFile();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE> GetExcelFileAsync() {
            return base.Channel.GetExcelFileAsync();
        }
        
        public void Delete(string programCode) {
            base.Channel.Delete(programCode);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string programCode) {
            return base.Channel.DeleteAsync(programCode);
        }
        
        public void DeleteImgSchedule(string programCode) {
            base.Channel.DeleteImgSchedule(programCode);
        }
        
        public System.Threading.Tasks.Task DeleteImgScheduleAsync(string programCode) {
            return base.Channel.DeleteImgScheduleAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowList[] GetWowListPartnerList(string programCode) {
            return base.Channel.GetWowListPartnerList(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowList[]> GetWowListPartnerListAsync(string programCode) {
            return base.Channel.GetWowListPartnerListAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_PARTNER[] GetProgramPartnerList(string programCode) {
            return base.Channel.GetProgramPartnerList(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_PARTNER[]> GetProgramPartnerListAsync(string programCode) {
            return base.Channel.GetProgramPartnerListAsync(programCode);
        }
        
        public void AddProgramPartner(string programCode, int payNo, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.AddProgramPartner(programCode, payNo, loginUser);
        }
        
        public System.Threading.Tasks.Task AddProgramPartnerAsync(string programCode, int payNo, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.AddProgramPartnerAsync(programCode, payNo, loginUser);
        }
        
        public void DeleteProgramPartner(string programCode, int payNo) {
            base.Channel.DeleteProgramPartner(programCode, payNo);
        }
        
        public System.Threading.Tasks.Task DeleteProgramPartnerAsync(string programCode, int payNo) {
            return base.Channel.DeleteProgramPartnerAsync(programCode, payNo);
        }
        
        public void DeleteProgramPartnerList(string programCode) {
            base.Channel.DeleteProgramPartnerList(programCode);
        }
        
        public System.Threading.Tasks.Task DeleteProgramPartnerListAsync(string programCode) {
            return base.Channel.DeleteProgramPartnerListAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_ADMIN[] GetProgramAdminList(string programCode) {
            return base.Channel.GetProgramAdminList(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_ADMIN[]> GetProgramAdminListAsync(string programCode) {
            return base.Channel.GetProgramAdminListAsync(programCode);
        }
        
        public void AddProgramAdmin(string programCode, int adminSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.AddProgramAdmin(programCode, adminSeq, loginUser);
        }
        
        public System.Threading.Tasks.Task AddProgramAdminAsync(string programCode, int adminSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.AddProgramAdminAsync(programCode, adminSeq, loginUser);
        }
        
        public void DeleteProgramAdmin(string programCode, int adminSeq) {
            base.Channel.DeleteProgramAdmin(programCode, adminSeq);
        }
        
        public System.Threading.Tasks.Task DeleteProgramAdminAsync(string programCode, int adminSeq) {
            return base.Channel.DeleteProgramAdminAsync(programCode, adminSeq);
        }
        
        public void DeleteProgramAdminList(string programCode) {
            base.Channel.DeleteProgramAdminList(programCode);
        }
        
        public System.Threading.Tasks.Task DeleteProgramAdminListAsync(string programCode) {
            return base.Channel.DeleteProgramAdminListAsync(programCode);
        }
        
        public string[] GetAdminProgram(int adminSeq) {
            return base.Channel.GetAdminProgram(adminSeq);
        }
        
        public System.Threading.Tasks.Task<string[]> GetAdminProgramAsync(int adminSeq) {
            return base.Channel.GetAdminProgramAsync(adminSeq);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN[] SearchListRunDown(string date) {
            return base.Channel.SearchListRunDown(date);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN[]> SearchListRunDownAsync(string date) {
            return base.Channel.SearchListRunDownAsync(date);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN GetNowRunDown() {
            return base.Channel.GetNowRunDown();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_RUNDOWN> GetNowRunDownAsync() {
            return base.Channel.GetNowRunDownAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.editVOD.tblStockClass[] GetListStockVod() {
            return base.Channel.GetListStockVod();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.editVOD.tblStockClass[]> GetListStockVodAsync() {
            return base.Channel.GetListStockVodAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NUP_BROAD_MAIN_ARTICLE_SELECT_Result[] GetListMarket() {
            return base.Channel.GetListMarket();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_BROAD_MAIN_ARTICLE_SELECT_Result[]> GetListMarketAsync() {
            return base.Channel.GetListMarketAsync();
        }
        
        public void ProgramOrder(Wow.Tv.Middle.Model.Db49.wowtv.TAB_PGM_ORDER model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile) {
            base.Channel.ProgramOrder(model, attachFile);
        }
        
        public System.Threading.Tasks.Task ProgramOrderAsync(Wow.Tv.Middle.Model.Db49.wowtv.TAB_PGM_ORDER model, Wow.Tv.Middle.Model.Db49.wowtv.NTB_ATTACH_FILE attachFile) {
            return base.Channel.ProgramOrderAsync(model, attachFile);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[] GetNotice1() {
            return base.Channel.GetNotice1();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[]> GetNotice1Async() {
            return base.Channel.GetNotice1Async();
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.TAB_LECTURES_SCHEDULE[] GetNotice2() {
            return base.Channel.GetNotice2();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.TAB_LECTURES_SCHEDULE[]> GetNotice2Async() {
            return base.Channel.GetNotice2Async();
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[] GetNotice3() {
            return base.Channel.GetNotice3();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT[]> GetNotice3Async() {
            return base.Channel.GetNotice3Async();
        }
        
        public bool IsHoliDayCheck() {
            return base.Channel.IsHoliDayCheck();
        }
        
        public System.Threading.Tasks.Task<bool> IsHoliDayCheckAsync() {
            return base.Channel.IsHoliDayCheckAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.BestStockPro[] GetWowNetData() {
            return base.Channel.GetWowNetData();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.BestStockPro[]> GetWowNetDataAsync() {
            return base.Channel.GetWowNetDataAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.USP_GetRecommendPro3_Result[] GetWowNetData2() {
            return base.Channel.GetWowNetData2();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.USP_GetRecommendPro3_Result[]> GetWowNetData2Async() {
            return base.Channel.GetWowNetData2Async();
        }
        
        public Wow.Tv.Middle.Model.Db16.wowfa.WOW_M_BANNER[] GetWowFaData() {
            return base.Channel.GetWowFaData();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db16.wowfa.WOW_M_BANNER[]> GetWowFaDataAsync() {
            return base.Channel.GetWowFaDataAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.NUP_MAIN_COMMON_LECTURE_SELECT_Result[] GetWowFaDataLecture() {
            return base.Channel.GetWowFaDataLecture();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.NUP_MAIN_COMMON_LECTURE_SELECT_Result[]> GetWowFaDataLectureAsync() {
            return base.Channel.GetWowFaDataLectureAsync();
        }
        
        public Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_video_Result[] GetWowStarData() {
            return base.Channel.GetWowStarData();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_video_Result[]> GetWowStarDataAsync() {
            return base.Channel.GetWowStarDataAsync();
        }
        
        public Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_p2p_wowtv_Result GetWowStarDataStock() {
            return base.Channel.GetWowStarDataStock();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db123.WOW4989.wowstar_p2p_wowtv_Result> GetWowStarDataStockAsync() {
            return base.Channel.GetWowStarDataStockAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.Pro_wow_junmunga_broadcast GetJunMunGaData(string proId) {
            return base.Channel.GetJunMunGaData(proId);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.Pro_wow_junmunga_broadcast> GetJunMunGaDataAsync(string proId) {
            return base.Channel.GetJunMunGaDataAsync(proId);
        }
        
        public Wow.Tv.Middle.Model.Common.DumyModel[] TickerList() {
            return base.Channel.TickerList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.DumyModel[]> TickerListAsync() {
            return base.Channel.TickerListAsync();
        }
        
        public int[] GetPartnerEventItemPrice(string proId) {
            return base.Channel.GetPartnerEventItemPrice(proId);
        }
        
        public System.Threading.Tasks.Task<int[]> GetPartnerEventItemPriceAsync(string proId) {
            return base.Channel.GetPartnerEventItemPriceAsync(proId);
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.USP_GetBroadcast1ByWellList_Result[] GetProWowWellList() {
            return base.Channel.GetProWowWellList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.USP_GetBroadcast1ByWellList_Result[]> GetProWowWellListAsync() {
            return base.Channel.GetProWowWellListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowListStockKing[] GetStockKing3() {
            return base.Channel.GetStockKing3();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.Pro_wowListStockKing[]> GetStockKing3Async() {
            return base.Channel.GetStockKing3Async();
        }
        
        public Wow.Tv.Middle.Model.Db49.wownet.USP_GetTabStrategetApplication_Result[] TodayStrategy() {
            return base.Channel.TodayStrategy();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wownet.USP_GetTabStrategetApplication_Result[]> TodayStrategyAsync() {
            return base.Channel.TodayStrategyAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.broadcast.usp_GetlivePro_Result[] GetOnAirPartnerList() {
            return base.Channel.GetOnAirPartnerList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.broadcast.usp_GetlivePro_Result[]> GetOnAirPartnerListAsync() {
            return base.Channel.GetOnAirPartnerListAsync();
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.usp_GetCornerVODList_WEB_Result> GetCornerVod(string scCode, int currentIndex, int pageSize) {
            return base.Channel.GetCornerVod(scCode, currentIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.usp_GetCornerVODList_WEB_Result>> GetCornerVodAsync(string scCode, int currentIndex, int pageSize) {
            return base.Channel.GetCornerVodAsync(scCode, currentIndex, pageSize);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.NUP_GetCornerVODList_WEB_Result> GetCornerVodAll(int currentIndex, int pageSize) {
            return base.Channel.GetCornerVodAll(currentIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.editVOD.NUP_GetCornerVODList_WEB_Result>> GetCornerVodAllAsync(int currentIndex, int pageSize) {
            return base.Channel.GetCornerVodAllAsync(currentIndex, pageSize);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU[] GetMenuByProgramCode(string programCode) {
            return base.Channel.GetMenuByProgramCode(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU[]> GetMenuByProgramCodeAsync(string programCode) {
            return base.Channel.GetMenuByProgramCodeAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU GetMenuByCornerSeq(string programCode, string scCode) {
            return base.Channel.GetMenuByCornerSeq(programCode, scCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MENU> GetMenuByCornerSeqAsync(string programCode, string scCode) {
            return base.Channel.GetMenuByCornerSeqAsync(programCode, scCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT GetTrade(int boardContentSeq) {
            return base.Channel.GetTrade(boardContentSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_BOARD_CONTENT> GetTradeAsync(int boardContentSeq) {
            return base.Channel.GetTradeAsync(boardContentSeq);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG> SearchListRandom() {
            return base.Channel.SearchListRandom();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG>> SearchListRandomAsync() {
            return base.Channel.SearchListRandomAsync();
        }
        
        public void Migration() {
            base.Channel.Migration();
        }
        
        public System.Threading.Tasks.Task MigrationAsync() {
            return base.Channel.MigrationAsync();
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[] GetMigrationProgramList() {
            return base.Channel.GetMigrationProgramList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[]> GetMigrationProgramListAsync() {
            return base.Channel.GetMigrationProgramListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.editVOD.tblSubConerList[] MigrationProgramCornerList(string programCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.MigrationProgramCornerList(programCode, loginUser);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.editVOD.tblSubConerList[]> MigrationProgramCornerListAsync(string programCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.MigrationProgramCornerListAsync(programCode, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramList_Result[] GetAllProgramList(string programNameStart, string programNameEnd, string year, int startIndex, int endIndex) {
            return base.Channel.GetAllProgramList(programNameStart, programNameEnd, year, startIndex, endIndex);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramList_Result[]> GetAllProgramListAsync(string programNameStart, string programNameEnd, string year, int startIndex, int endIndex) {
            return base.Channel.GetAllProgramListAsync(programNameStart, programNameEnd, year, startIndex, endIndex);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramEtcList_Result[] GetAllProgramEtcList(string year, int startIndex, int endIndex) {
            return base.Channel.GetAllProgramEtcList(year, startIndex, endIndex);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.NUP_GetAllProgramEtcList_Result[]> GetAllProgramEtcListAsync(string year, int startIndex, int endIndex) {
            return base.Channel.GetAllProgramEtcListAsync(year, startIndex, endIndex);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BroadService.IProgramCmsAuthService")]
    public interface IProgramCmsAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramCmsAuthService/CmsMainFileMigration", ReplyAction="http://tempuri.org/IProgramCmsAuthService/CmsMainFileMigrationResponse")]
        void CmsMainFileMigration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramCmsAuthService/CmsMainFileMigration", ReplyAction="http://tempuri.org/IProgramCmsAuthService/CmsMainFileMigrationResponse")]
        System.Threading.Tasks.Task CmsMainFileMigrationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProgramCmsAuthServiceChannel : Wow.Tv.FrontWebMobile.BroadService.IProgramCmsAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgramCmsAuthServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.BroadService.IProgramCmsAuthService>, Wow.Tv.FrontWebMobile.BroadService.IProgramCmsAuthService {
        
        public ProgramCmsAuthServiceClient() {
        }
        
        public ProgramCmsAuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgramCmsAuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramCmsAuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramCmsAuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CmsMainFileMigration() {
            base.Channel.CmsMainFileMigration();
        }
        
        public System.Threading.Tasks.Task CmsMainFileMigrationAsync() {
            return base.Channel.CmsMainFileMigrationAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BroadService.IProgramGroupService")]
    public interface IProgramGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/GetAtProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/GetAtProgramGroupResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP GetAtProgramGroup(int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/GetAtProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/GetAtProgramGroupResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP> GetAtProgramGroupAsync(int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/GetAtByMainCode", ReplyAction="http://tempuri.org/IProgramGroupService/GetAtByMainCodeResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP GetAtByMainCode(string masterProgramCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/GetAtByMainCode", ReplyAction="http://tempuri.org/IProgramGroupService/GetAtByMainCodeResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP> GetAtByMainCodeAsync(string masterProgramCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/SearchListProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/SearchListProgramGroupResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP> SearchListProgramGroup(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadGroupCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/SearchListProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/SearchListProgramGroupResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP>> SearchListProgramGroupAsync(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadGroupCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/SaveProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/SaveProgramGroupResponse")]
        int SaveProgramGroup(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/SaveProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/SaveProgramGroupResponse")]
        System.Threading.Tasks.Task<int> SaveProgramGroupAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/DeleteProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/DeleteProgramGroupResponse")]
        void DeleteProgramGroup(int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/DeleteProgramGroup", ReplyAction="http://tempuri.org/IProgramGroupService/DeleteProgramGroupResponse")]
        System.Threading.Tasks.Task DeleteProgramGroupAsync(int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/DeleteProgramGroupList", ReplyAction="http://tempuri.org/IProgramGroupService/DeleteProgramGroupListResponse")]
        void DeleteProgramGroupList(int[] seqList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramGroupService/DeleteProgramGroupList", ReplyAction="http://tempuri.org/IProgramGroupService/DeleteProgramGroupListResponse")]
        System.Threading.Tasks.Task DeleteProgramGroupListAsync(int[] seqList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProgramGroupServiceChannel : Wow.Tv.FrontWebMobile.BroadService.IProgramGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgramGroupServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.BroadService.IProgramGroupService>, Wow.Tv.FrontWebMobile.BroadService.IProgramGroupService {
        
        public ProgramGroupServiceClient() {
        }
        
        public ProgramGroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgramGroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramGroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP GetAtProgramGroup(int programGroupSeq) {
            return base.Channel.GetAtProgramGroup(programGroupSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP> GetAtProgramGroupAsync(int programGroupSeq) {
            return base.Channel.GetAtProgramGroupAsync(programGroupSeq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP GetAtByMainCode(string masterProgramCode) {
            return base.Channel.GetAtByMainCode(masterProgramCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP> GetAtByMainCodeAsync(string masterProgramCode) {
            return base.Channel.GetAtByMainCodeAsync(masterProgramCode);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP> SearchListProgramGroup(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadGroupCondition condition) {
            return base.Channel.SearchListProgramGroup(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP>> SearchListProgramGroupAsync(Wow.Tv.Middle.Model.Db49.wowtv.Broad.BroadGroupCondition condition) {
            return base.Channel.SearchListProgramGroupAsync(condition);
        }
        
        public int SaveProgramGroup(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveProgramGroup(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveProgramGroupAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveProgramGroupAsync(model, loginUser);
        }
        
        public void DeleteProgramGroup(int programGroupSeq) {
            base.Channel.DeleteProgramGroup(programGroupSeq);
        }
        
        public System.Threading.Tasks.Task DeleteProgramGroupAsync(int programGroupSeq) {
            return base.Channel.DeleteProgramGroupAsync(programGroupSeq);
        }
        
        public void DeleteProgramGroupList(int[] seqList) {
            base.Channel.DeleteProgramGroupList(seqList);
        }
        
        public System.Threading.Tasks.Task DeleteProgramGroupListAsync(int[] seqList) {
            return base.Channel.DeleteProgramGroupListAsync(seqList);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BroadService.IProgramTemplateService")]
    public interface IProgramTemplateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetAtProgramTemplate", ReplyAction="http://tempuri.org/IProgramTemplateService/GetAtProgramTemplateResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE GetAtProgramTemplate(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetAtProgramTemplate", ReplyAction="http://tempuri.org/IProgramTemplateService/GetAtProgramTemplateResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE> GetAtProgramTemplateAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/SaveProgramTemplate", ReplyAction="http://tempuri.org/IProgramTemplateService/SaveProgramTemplateResponse")]
        int SaveProgramTemplate(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE model, Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG newsProgram, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/SaveProgramTemplate", ReplyAction="http://tempuri.org/IProgramTemplateService/SaveProgramTemplateResponse")]
        System.Threading.Tasks.Task<int> SaveProgramTemplateAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE model, Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG newsProgram, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplate", ReplyAction="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateResponse")]
        void DeleteProgramTemplate(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplate", ReplyAction="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateResponse")]
        System.Threading.Tasks.Task DeleteProgramTemplateAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupList", ReplyAction="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupListResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP[] GetProgramTemplateGroupList(int programTemplateSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupList", ReplyAction="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP[]> GetProgramTemplateGroupListAsync(int programTemplateSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupListByGroupSeq", ReplyAction="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupListByGroupSeqR" +
            "esponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE_GROUP[] GetProgramTemplateGroupListByGroupSeq(int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupListByGroupSeq", ReplyAction="http://tempuri.org/IProgramTemplateService/GetProgramTemplateGroupListByGroupSeqR" +
            "esponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE_GROUP[]> GetProgramTemplateGroupListByGroupSeqAsync(int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/AddProgramTemplateGroup", ReplyAction="http://tempuri.org/IProgramTemplateService/AddProgramTemplateGroupResponse")]
        void AddProgramTemplateGroup(int programTemplateSeq, int programGroupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/AddProgramTemplateGroup", ReplyAction="http://tempuri.org/IProgramTemplateService/AddProgramTemplateGroupResponse")]
        System.Threading.Tasks.Task AddProgramTemplateGroupAsync(int programTemplateSeq, int programGroupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroup", ReplyAction="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroupResponse")]
        void DeleteProgramTemplateGroup(int programTemplateSeq, int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroup", ReplyAction="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroupResponse")]
        System.Threading.Tasks.Task DeleteProgramTemplateGroupAsync(int programTemplateSeq, int programGroupSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroupList", ReplyAction="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroupListResponse" +
            "")]
        void DeleteProgramTemplateGroupList(int programTemplateSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroupList", ReplyAction="http://tempuri.org/IProgramTemplateService/DeleteProgramTemplateGroupListResponse" +
            "")]
        System.Threading.Tasks.Task DeleteProgramTemplateGroupListAsync(int programTemplateSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/UpDownProgramTemplateGroupList", ReplyAction="http://tempuri.org/IProgramTemplateService/UpDownProgramTemplateGroupListResponse" +
            "")]
        void UpDownProgramTemplateGroupList(int programTemplateSeq, int programGroupSeq, bool isUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/UpDownProgramTemplateGroupList", ReplyAction="http://tempuri.org/IProgramTemplateService/UpDownProgramTemplateGroupListResponse" +
            "")]
        System.Threading.Tasks.Task UpDownProgramTemplateGroupListAsync(int programTemplateSeq, int programGroupSeq, bool isUp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetFamilyList", ReplyAction="http://tempuri.org/IProgramTemplateService/GetFamilyListResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[] GetFamilyList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetFamilyList", ReplyAction="http://tempuri.org/IProgramTemplateService/GetFamilyListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[]> GetFamilyListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetChildList", ReplyAction="http://tempuri.org/IProgramTemplateService/GetChildListResponse")]
        Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[] GetChildList(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetChildList", ReplyAction="http://tempuri.org/IProgramTemplateService/GetChildListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[]> GetChildListAsync(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetProgramType", ReplyAction="http://tempuri.org/IProgramTemplateService/GetProgramTypeResponse")]
        string GetProgramType(string programCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramTemplateService/GetProgramType", ReplyAction="http://tempuri.org/IProgramTemplateService/GetProgramTypeResponse")]
        System.Threading.Tasks.Task<string> GetProgramTypeAsync(string programCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProgramTemplateServiceChannel : Wow.Tv.FrontWebMobile.BroadService.IProgramTemplateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgramTemplateServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.BroadService.IProgramTemplateService>, Wow.Tv.FrontWebMobile.BroadService.IProgramTemplateService {
        
        public ProgramTemplateServiceClient() {
        }
        
        public ProgramTemplateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgramTemplateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramTemplateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramTemplateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE GetAtProgramTemplate(string programCode) {
            return base.Channel.GetAtProgramTemplate(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE> GetAtProgramTemplateAsync(string programCode) {
            return base.Channel.GetAtProgramTemplateAsync(programCode);
        }
        
        public int SaveProgramTemplate(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE model, Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG newsProgram, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveProgramTemplate(model, newsProgram, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveProgramTemplateAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE model, Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG newsProgram, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveProgramTemplateAsync(model, newsProgram, loginUser);
        }
        
        public void DeleteProgramTemplate(string programCode) {
            base.Channel.DeleteProgramTemplate(programCode);
        }
        
        public System.Threading.Tasks.Task DeleteProgramTemplateAsync(string programCode) {
            return base.Channel.DeleteProgramTemplateAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP[] GetProgramTemplateGroupList(int programTemplateSeq) {
            return base.Channel.GetProgramTemplateGroupList(programTemplateSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_GROUP[]> GetProgramTemplateGroupListAsync(int programTemplateSeq) {
            return base.Channel.GetProgramTemplateGroupListAsync(programTemplateSeq);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE_GROUP[] GetProgramTemplateGroupListByGroupSeq(int programGroupSeq) {
            return base.Channel.GetProgramTemplateGroupListByGroupSeq(programGroupSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_PROGRAM_TEMPLATE_GROUP[]> GetProgramTemplateGroupListByGroupSeqAsync(int programGroupSeq) {
            return base.Channel.GetProgramTemplateGroupListByGroupSeqAsync(programGroupSeq);
        }
        
        public void AddProgramTemplateGroup(int programTemplateSeq, int programGroupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.AddProgramTemplateGroup(programTemplateSeq, programGroupSeq, loginUser);
        }
        
        public System.Threading.Tasks.Task AddProgramTemplateGroupAsync(int programTemplateSeq, int programGroupSeq, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.AddProgramTemplateGroupAsync(programTemplateSeq, programGroupSeq, loginUser);
        }
        
        public void DeleteProgramTemplateGroup(int programTemplateSeq, int programGroupSeq) {
            base.Channel.DeleteProgramTemplateGroup(programTemplateSeq, programGroupSeq);
        }
        
        public System.Threading.Tasks.Task DeleteProgramTemplateGroupAsync(int programTemplateSeq, int programGroupSeq) {
            return base.Channel.DeleteProgramTemplateGroupAsync(programTemplateSeq, programGroupSeq);
        }
        
        public void DeleteProgramTemplateGroupList(int programTemplateSeq) {
            base.Channel.DeleteProgramTemplateGroupList(programTemplateSeq);
        }
        
        public System.Threading.Tasks.Task DeleteProgramTemplateGroupListAsync(int programTemplateSeq) {
            return base.Channel.DeleteProgramTemplateGroupListAsync(programTemplateSeq);
        }
        
        public void UpDownProgramTemplateGroupList(int programTemplateSeq, int programGroupSeq, bool isUp) {
            base.Channel.UpDownProgramTemplateGroupList(programTemplateSeq, programGroupSeq, isUp);
        }
        
        public System.Threading.Tasks.Task UpDownProgramTemplateGroupListAsync(int programTemplateSeq, int programGroupSeq, bool isUp) {
            return base.Channel.UpDownProgramTemplateGroupListAsync(programTemplateSeq, programGroupSeq, isUp);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[] GetFamilyList(string programCode) {
            return base.Channel.GetFamilyList(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[]> GetFamilyListAsync(string programCode) {
            return base.Channel.GetFamilyListAsync(programCode);
        }
        
        public Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[] GetChildList(string programCode) {
            return base.Channel.GetChildList(programCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db90.DNRS.T_NEWS_PRG[]> GetChildListAsync(string programCode) {
            return base.Channel.GetChildListAsync(programCode);
        }
        
        public string GetProgramType(string programCode) {
            return base.Channel.GetProgramType(programCode);
        }
        
        public System.Threading.Tasks.Task<string> GetProgramTypeAsync(string programCode) {
            return base.Channel.GetProgramTypeAsync(programCode);
        }
    }
}
