//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.CommconCodeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommconCodeService.ICommconCodeService")]
    public interface ICommconCodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/SearchList", ReplyAction="http://tempuri.org/ICommconCodeService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.CommonCode.CommonCodeCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/SearchList", ReplyAction="http://tempuri.org/ICommconCodeService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.CommonCode.CommonCodeCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/GetAt", ReplyAction="http://tempuri.org/ICommconCodeService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE GetAt(string commonCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/GetAt", ReplyAction="http://tempuri.org/ICommconCodeService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE> GetAtAsync(string commonCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/GetAtFromValue", ReplyAction="http://tempuri.org/ICommconCodeService/GetAtFromValueResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE GetAtFromValue(string upCommonCode, string codeValue1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/GetAtFromValue", ReplyAction="http://tempuri.org/ICommconCodeService/GetAtFromValueResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE> GetAtFromValueAsync(string upCommonCode, string codeValue1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/Save", ReplyAction="http://tempuri.org/ICommconCodeService/SaveResponse")]
        string Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/Save", ReplyAction="http://tempuri.org/ICommconCodeService/SaveResponse")]
        System.Threading.Tasks.Task<string> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/Delete", ReplyAction="http://tempuri.org/ICommconCodeService/DeleteResponse")]
        void Delete(string commonCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommconCodeService/Delete", ReplyAction="http://tempuri.org/ICommconCodeService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string commonCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommconCodeServiceChannel : Wow.Tv.FrontWeb.CommconCodeService.ICommconCodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommconCodeServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.CommconCodeService.ICommconCodeService>, Wow.Tv.FrontWeb.CommconCodeService.ICommconCodeService {
        
        public CommconCodeServiceClient() {
        }
        
        public CommconCodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommconCodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommconCodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommconCodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.CommonCode.CommonCodeCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.CommonCode.CommonCodeCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE GetAt(string commonCode) {
            return base.Channel.GetAt(commonCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE> GetAtAsync(string commonCode) {
            return base.Channel.GetAtAsync(commonCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE GetAtFromValue(string upCommonCode, string codeValue1) {
            return base.Channel.GetAtFromValue(upCommonCode, codeValue1);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE> GetAtFromValueAsync(string upCommonCode, string codeValue1) {
            return base.Channel.GetAtFromValueAsync(upCommonCode, codeValue1);
        }
        
        public string Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<string> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_COMMON_CODE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(string commonCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.Delete(commonCode, loginUser);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string commonCode, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.DeleteAsync(commonCode, loginUser);
        }
    }
}
