//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.NewsAdService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsAdService.INewsAdService")]
    public interface INewsAdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsAdService/GetHardCodingAdList", ReplyAction="http://tempuri.org/INewsAdService/GetHardCodingAdListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD> GetHardCodingAdList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsAdService/GetHardCodingAdList", ReplyAction="http://tempuri.org/INewsAdService/GetHardCodingAdListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD>> GetHardCodingAdListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsAdService/GetHardCodingAdInfo", ReplyAction="http://tempuri.org/INewsAdService/GetHardCodingAdInfoResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD GetHardCodingAdInfo(int SEQ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsAdService/GetHardCodingAdInfo", ReplyAction="http://tempuri.org/INewsAdService/GetHardCodingAdInfoResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD> GetHardCodingAdInfoAsync(int SEQ);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsAdService/SetHardCodingAd", ReplyAction="http://tempuri.org/INewsAdService/SetHardCodingAdResponse")]
        bool SetHardCodingAd(Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD hardCodingAdInfo, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsAdService/SetHardCodingAd", ReplyAction="http://tempuri.org/INewsAdService/SetHardCodingAdResponse")]
        System.Threading.Tasks.Task<bool> SetHardCodingAdAsync(Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD hardCodingAdInfo, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsAdServiceChannel : Wow.Tv.FrontWeb.NewsAdService.INewsAdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsAdServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.NewsAdService.INewsAdService>, Wow.Tv.FrontWeb.NewsAdService.INewsAdService {
        
        public NewsAdServiceClient() {
        }
        
        public NewsAdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsAdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsAdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsAdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD> GetHardCodingAdList() {
            return base.Channel.GetHardCodingAdList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD>> GetHardCodingAdListAsync() {
            return base.Channel.GetHardCodingAdListAsync();
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD GetHardCodingAdInfo(int SEQ) {
            return base.Channel.GetHardCodingAdInfo(SEQ);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD> GetHardCodingAdInfoAsync(int SEQ) {
            return base.Channel.GetHardCodingAdInfoAsync(SEQ);
        }
        
        public bool SetHardCodingAd(Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD hardCodingAdInfo, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SetHardCodingAd(hardCodingAdInfo, loginUser);
        }
        
        public System.Threading.Tasks.Task<bool> SetHardCodingAdAsync(Wow.Tv.Middle.Model.Db49.Article.NTB_HARD_CODING_AD hardCodingAdInfo, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SetHardCodingAdAsync(hardCodingAdInfo, loginUser);
        }
    }
}
