//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.NewsGFCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsGFCService.INewsGFCService")]
    public interface INewsGFCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsGFCService/NewsGFCList", ReplyAction="http://tempuri.org/INewsGFCService/NewsGFCListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsGFCList> NewsGFCList(string searchYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsGFCService/NewsGFCList", ReplyAction="http://tempuri.org/INewsGFCService/NewsGFCListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsGFCList>> NewsGFCListAsync(string searchYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsGFCService/NewsGFCView", ReplyAction="http://tempuri.org/INewsGFCService/NewsGFCViewResponse")]
        Wow.Tv.Middle.Model.Db49.Article.usp_WOWTVNewsCenterView_Result NewsGFCView(string artid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsGFCService/NewsGFCView", ReplyAction="http://tempuri.org/INewsGFCService/NewsGFCViewResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.usp_WOWTVNewsCenterView_Result> NewsGFCViewAsync(string artid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsGFCService/sendEmailGFC", ReplyAction="http://tempuri.org/INewsGFCService/sendEmailGFCResponse")]
        void sendEmailGFC(string email, string year, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsGFCService/sendEmailGFC", ReplyAction="http://tempuri.org/INewsGFCService/sendEmailGFCResponse")]
        System.Threading.Tasks.Task sendEmailGFCAsync(string email, string year, string language);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsGFCServiceChannel : Wow.Tv.FrontWeb.NewsGFCService.INewsGFCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsGFCServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.NewsGFCService.INewsGFCService>, Wow.Tv.FrontWeb.NewsGFCService.INewsGFCService {
        
        public NewsGFCServiceClient() {
        }
        
        public NewsGFCServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsGFCServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsGFCServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsGFCServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsGFCList> NewsGFCList(string searchYear) {
            return base.Channel.NewsGFCList(searchYear);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsGFCList>> NewsGFCListAsync(string searchYear) {
            return base.Channel.NewsGFCListAsync(searchYear);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.usp_WOWTVNewsCenterView_Result NewsGFCView(string artid) {
            return base.Channel.NewsGFCView(artid);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.usp_WOWTVNewsCenterView_Result> NewsGFCViewAsync(string artid) {
            return base.Channel.NewsGFCViewAsync(artid);
        }
        
        public void sendEmailGFC(string email, string year, string language) {
            base.Channel.sendEmailGFC(email, year, language);
        }
        
        public System.Threading.Tasks.Task sendEmailGFCAsync(string email, string year, string language) {
            return base.Channel.sendEmailGFCAsync(email, year, language);
        }
    }
}
