//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.OpinionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpinionService.IOpinionService")]
    public interface IOpinionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/GetColumnList", ReplyAction="http://tempuri.org/IOpinionService/GetColumnListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionColumnModel> GetColumnList(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/GetColumnList", ReplyAction="http://tempuri.org/IOpinionService/GetColumnListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionColumnModel>> GetColumnListAsync(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/GetDetailList", ReplyAction="http://tempuri.org/IOpinionService/GetDetailListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_SECTION_SELECT_Result> GetDetailList(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/GetDetailList", ReplyAction="http://tempuri.org/IOpinionService/GetDetailListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_SECTION_SELECT_Result>> GetDetailListAsync(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/GetPlanList", ReplyAction="http://tempuri.org/IOpinionService/GetPlanListResponse")]
        Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle[] GetPlanList(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/GetPlanList", ReplyAction="http://tempuri.org/IOpinionService/GetPlanListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle[]> GetPlanListAsync(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/ColumnBannerImg", ReplyAction="http://tempuri.org/IOpinionService/ColumnBannerImgResponse")]
        Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle ColumnBannerImg(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpinionService/ColumnBannerImg", ReplyAction="http://tempuri.org/IOpinionService/ColumnBannerImgResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle> ColumnBannerImgAsync(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOpinionServiceChannel : Wow.Tv.FrontWeb.OpinionService.IOpinionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpinionServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.OpinionService.IOpinionService>, Wow.Tv.FrontWeb.OpinionService.IOpinionService {
        
        public OpinionServiceClient() {
        }
        
        public OpinionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpinionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpinionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpinionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionColumnModel> GetColumnList(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition) {
            return base.Channel.GetColumnList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionColumnModel>> GetColumnListAsync(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition) {
            return base.Channel.GetColumnListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_SECTION_SELECT_Result> GetDetailList(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition, string text) {
            return base.Channel.GetDetailList(condition, text);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_SECTION_SELECT_Result>> GetDetailListAsync(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition, string text) {
            return base.Channel.GetDetailListAsync(condition, text);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle[] GetPlanList(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition) {
            return base.Channel.GetPlanList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle[]> GetPlanListAsync(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition) {
            return base.Channel.GetPlanListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle ColumnBannerImg(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition) {
            return base.Channel.ColumnBannerImg(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.tblPlanArticle> ColumnBannerImgAsync(Wow.Tv.Middle.Model.Db49.Article.Opinion.OpinionCondition condition) {
            return base.Channel.ColumnBannerImgAsync(condition);
        }
    }
}
