//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.NewsQuickMenuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsQuickMenuService.IQuickMenuService")]
    public interface IQuickMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinReporter", ReplyAction="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinReporterResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_REPORTER_SELECT_Result[] GetQuickMenuMypinReporter(string userID, System.Nullable<int> topN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinReporter", ReplyAction="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinReporterResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_REPORTER_SELECT_Result[]> GetQuickMenuMypinReporterAsync(string userID, System.Nullable<int> topN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinNews", ReplyAction="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinNewsResponse")]
        Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_NEWS_SELECT_Result[] GetQuickMenuMypinNews(string userID, System.Nullable<int> topN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinNews", ReplyAction="http://tempuri.org/IQuickMenuService/GetQuickMenuMypinNewsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_NEWS_SELECT_Result[]> GetQuickMenuMypinNewsAsync(string userID, System.Nullable<int> topN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuickMenuServiceChannel : Wow.Tv.FrontWeb.NewsQuickMenuService.IQuickMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuickMenuServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.NewsQuickMenuService.IQuickMenuService>, Wow.Tv.FrontWeb.NewsQuickMenuService.IQuickMenuService {
        
        public QuickMenuServiceClient() {
        }
        
        public QuickMenuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuickMenuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuickMenuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuickMenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_REPORTER_SELECT_Result[] GetQuickMenuMypinReporter(string userID, System.Nullable<int> topN) {
            return base.Channel.GetQuickMenuMypinReporter(userID, topN);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_REPORTER_SELECT_Result[]> GetQuickMenuMypinReporterAsync(string userID, System.Nullable<int> topN) {
            return base.Channel.GetQuickMenuMypinReporterAsync(userID, topN);
        }
        
        public Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_NEWS_SELECT_Result[] GetQuickMenuMypinNews(string userID, System.Nullable<int> topN) {
            return base.Channel.GetQuickMenuMypinNews(userID, topN);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.Article.NUP_QUICKMENU_MYPIN_NEWS_SELECT_Result[]> GetQuickMenuMypinNewsAsync(string userID, System.Nullable<int> topN) {
            return base.Channel.GetQuickMenuMypinNewsAsync(userID, topN);
        }
    }
}
