//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWebMobile.CharacterStockService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CharacterStockService.ICharacterStockService")]
    public interface ICharacterStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetCurrentPrice", ReplyAction="http://tempuri.org/ICharacterStockService/GetCurrentPriceResponse")]
        Wow.Tv.Middle.Model.Db22.stock.usp_GetStockPrice_Result GetCurrentPrice(string stockCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetCurrentPrice", ReplyAction="http://tempuri.org/ICharacterStockService/GetCurrentPriceResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db22.stock.usp_GetStockPrice_Result> GetCurrentPriceAsync(string stockCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetStockVODList", ReplyAction="http://tempuri.org/ICharacterStockService/GetStockVODListResponse")]
        Wow.Tv.Middle.Model.Db49.editVOD.usp_byStockCodeGetVOD_Result[] GetStockVODList(string stockCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetStockVODList", ReplyAction="http://tempuri.org/ICharacterStockService/GetStockVODListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.editVOD.usp_byStockCodeGetVOD_Result[]> GetStockVODListAsync(string stockCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetCharaterStockList", ReplyAction="http://tempuri.org/ICharacterStockService/GetCharaterStockListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.Finance.CharacterStockModel> GetCharaterStockList(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetCharaterStockList", ReplyAction="http://tempuri.org/ICharacterStockService/GetCharaterStockListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.Finance.CharacterStockModel>> GetCharaterStockListAsync(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetMinArtdate", ReplyAction="http://tempuri.org/ICharacterStockService/GetMinArtdateResponse")]
        string GetMinArtdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharacterStockService/GetMinArtdate", ReplyAction="http://tempuri.org/ICharacterStockService/GetMinArtdateResponse")]
        System.Threading.Tasks.Task<string> GetMinArtdateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICharacterStockServiceChannel : Wow.Tv.FrontWebMobile.CharacterStockService.ICharacterStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CharacterStockServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWebMobile.CharacterStockService.ICharacterStockService>, Wow.Tv.FrontWebMobile.CharacterStockService.ICharacterStockService {
        
        public CharacterStockServiceClient() {
        }
        
        public CharacterStockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CharacterStockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharacterStockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharacterStockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db22.stock.usp_GetStockPrice_Result GetCurrentPrice(string stockCode) {
            return base.Channel.GetCurrentPrice(stockCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db22.stock.usp_GetStockPrice_Result> GetCurrentPriceAsync(string stockCode) {
            return base.Channel.GetCurrentPriceAsync(stockCode);
        }
        
        public Wow.Tv.Middle.Model.Db49.editVOD.usp_byStockCodeGetVOD_Result[] GetStockVODList(string stockCode) {
            return base.Channel.GetStockVODList(stockCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.editVOD.usp_byStockCodeGetVOD_Result[]> GetStockVODListAsync(string stockCode) {
            return base.Channel.GetStockVODListAsync(stockCode);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.Finance.CharacterStockModel> GetCharaterStockList(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition) {
            return base.Channel.GetCharaterStockList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db22.stock.Finance.CharacterStockModel>> GetCharaterStockListAsync(Wow.Tv.Middle.Model.Db49.Article.NewsCenter.NewsCenterCondition condition) {
            return base.Channel.GetCharaterStockListAsync(condition);
        }
        
        public string GetMinArtdate() {
            return base.Channel.GetMinArtdate();
        }
        
        public System.Threading.Tasks.Task<string> GetMinArtdateAsync() {
            return base.Channel.GetMinArtdateAsync();
        }
    }
}
