//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.MemberJoinService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemberJoinService.IJoinService")]
    public interface IJoinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/JoinCheckIpin", ReplyAction="http://tempuri.org/IJoinService/JoinCheckIpinResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckIpinResult JoinCheckIpin(string encryptedData, string parameter1, string parameter2, string parameter3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/JoinCheckIpin", ReplyAction="http://tempuri.org/IJoinService/JoinCheckIpinResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckIpinResult> JoinCheckIpinAsync(string encryptedData, string parameter1, string parameter2, string parameter3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/JoinCheckSms", ReplyAction="http://tempuri.org/IJoinService/JoinCheckSmsResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckSmsResult JoinCheckSms(string requestNo, string encryptedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/JoinCheckSms", ReplyAction="http://tempuri.org/IJoinService/JoinCheckSmsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckSmsResult> JoinCheckSmsAsync(string requestNo, string encryptedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/JoinCheckForeign", ReplyAction="http://tempuri.org/IJoinService/JoinCheckForeignResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckForeignResult JoinCheckForeign(string name, string ssno1, string ssno2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/JoinCheckForeign", ReplyAction="http://tempuri.org/IJoinService/JoinCheckForeignResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckForeignResult> JoinCheckForeignAsync(string name, string ssno1, string ssno2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserIpin", ReplyAction="http://tempuri.org/IJoinService/RegistUserIpinResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserIpin(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserIpin", ReplyAction="http://tempuri.org/IJoinService/RegistUserIpinResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserIpinAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserSms", ReplyAction="http://tempuri.org/IJoinService/RegistUserSmsResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserSms(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserSms", ReplyAction="http://tempuri.org/IJoinService/RegistUserSmsResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserSmsAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserForeign", ReplyAction="http://tempuri.org/IJoinService/RegistUserForeignResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserForeign(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserForeign", ReplyAction="http://tempuri.org/IJoinService/RegistUserForeignResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserForeignAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserCompany", ReplyAction="http://tempuri.org/IJoinService/RegistUserCompanyResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserCompany(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/RegistUserCompany", ReplyAction="http://tempuri.org/IJoinService/RegistUserCompanyResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserCompanyAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/GetSido", ReplyAction="http://tempuri.org/IJoinService/GetSidoResponse")]
        string[] GetSido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/GetSido", ReplyAction="http://tempuri.org/IJoinService/GetSidoResponse")]
        System.Threading.Tasks.Task<string[]> GetSidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/GetGugun", ReplyAction="http://tempuri.org/IJoinService/GetGugunResponse")]
        string[] GetGugun(string sido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/GetGugun", ReplyAction="http://tempuri.org/IJoinService/GetGugunResponse")]
        System.Threading.Tasks.Task<string[]> GetGugunAsync(string sido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/GetAddress", ReplyAction="http://tempuri.org/IJoinService/GetAddressResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.tblPost[] GetAddress(string searchKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/GetAddress", ReplyAction="http://tempuri.org/IJoinService/GetAddressResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblPost[]> GetAddressAsync(string searchKeyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/IsUserIdDuplicated", ReplyAction="http://tempuri.org/IJoinService/IsUserIdDuplicatedResponse")]
        bool IsUserIdDuplicated(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/IsUserIdDuplicated", ReplyAction="http://tempuri.org/IJoinService/IsUserIdDuplicatedResponse")]
        System.Threading.Tasks.Task<bool> IsUserIdDuplicatedAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/IsNickNameDuplicated", ReplyAction="http://tempuri.org/IJoinService/IsNickNameDuplicatedResponse")]
        bool IsNickNameDuplicated(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/IsNickNameDuplicated", ReplyAction="http://tempuri.org/IJoinService/IsNickNameDuplicatedResponse")]
        System.Threading.Tasks.Task<bool> IsNickNameDuplicatedAsync(string nickName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/MobileSendSMS", ReplyAction="http://tempuri.org/IJoinService/MobileSendSMSResponse")]
        string MobileSendSMS(string mobile1, string mobile2, string mobile3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/MobileSendSMS", ReplyAction="http://tempuri.org/IJoinService/MobileSendSMSResponse")]
        System.Threading.Tasks.Task<string> MobileSendSMSAsync(string mobile1, string mobile2, string mobile3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/CompanyExists", ReplyAction="http://tempuri.org/IJoinService/CompanyExistsResponse")]
        bool CompanyExists(string ssno1, string ssno2, string ssno3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/CompanyExists", ReplyAction="http://tempuri.org/IJoinService/CompanyExistsResponse")]
        System.Threading.Tasks.Task<bool> CompanyExistsAsync(string ssno1, string ssno2, string ssno3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/EmailAuth", ReplyAction="http://tempuri.org/IJoinService/EmailAuthResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthResult EmailAuth(int userNumber, string email, bool isMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/EmailAuth", ReplyAction="http://tempuri.org/IJoinService/EmailAuthResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthResult> EmailAuthAsync(int userNumber, string email, bool isMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/EmailAuthComplete", ReplyAction="http://tempuri.org/IJoinService/EmailAuthCompleteResponse")]
        Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthCompleteResult EmailAuthComplete(int userNumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/EmailAuthComplete", ReplyAction="http://tempuri.org/IJoinService/EmailAuthCompleteResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthCompleteResult> EmailAuthCompleteAsync(int userNumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/BillingServiceTest", ReplyAction="http://tempuri.org/IJoinService/BillingServiceTestResponse")]
        void BillingServiceTest(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/BillingServiceTest", ReplyAction="http://tempuri.org/IJoinService/BillingServiceTestResponse")]
        System.Threading.Tasks.Task BillingServiceTestAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/EmailSendTest", ReplyAction="http://tempuri.org/IJoinService/EmailSendTestResponse")]
        void EmailSendTest(string mailCode, string toName, string toEmail, string fromName, string fromEmail, string subject, string contents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinService/EmailSendTest", ReplyAction="http://tempuri.org/IJoinService/EmailSendTestResponse")]
        System.Threading.Tasks.Task EmailSendTestAsync(string mailCode, string toName, string toEmail, string fromName, string fromEmail, string subject, string contents);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJoinServiceChannel : Wow.Tv.FrontWeb.MemberJoinService.IJoinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JoinServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.MemberJoinService.IJoinService>, Wow.Tv.FrontWeb.MemberJoinService.IJoinService {
        
        public JoinServiceClient() {
        }
        
        public JoinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JoinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckIpinResult JoinCheckIpin(string encryptedData, string parameter1, string parameter2, string parameter3) {
            return base.Channel.JoinCheckIpin(encryptedData, parameter1, parameter2, parameter3);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckIpinResult> JoinCheckIpinAsync(string encryptedData, string parameter1, string parameter2, string parameter3) {
            return base.Channel.JoinCheckIpinAsync(encryptedData, parameter1, parameter2, parameter3);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckSmsResult JoinCheckSms(string requestNo, string encryptedData) {
            return base.Channel.JoinCheckSms(requestNo, encryptedData);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckSmsResult> JoinCheckSmsAsync(string requestNo, string encryptedData) {
            return base.Channel.JoinCheckSmsAsync(requestNo, encryptedData);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckForeignResult JoinCheckForeign(string name, string ssno1, string ssno2) {
            return base.Channel.JoinCheckForeign(name, ssno1, ssno2);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.JoinCheckForeignResult> JoinCheckForeignAsync(string name, string ssno1, string ssno2) {
            return base.Channel.JoinCheckForeignAsync(name, ssno1, ssno2);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserIpin(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserIpin(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserIpinAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserIpinAsync(request);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserSms(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserSms(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserSmsAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserSmsAsync(request);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserForeign(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserForeign(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserForeignAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserForeignAsync(request);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult RegistUserCompany(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserCompany(request);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserResult> RegistUserCompanyAsync(Wow.Tv.Middle.Model.Db89.wowbill.Member.RegistUserRequest request) {
            return base.Channel.RegistUserCompanyAsync(request);
        }
        
        public string[] GetSido() {
            return base.Channel.GetSido();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSidoAsync() {
            return base.Channel.GetSidoAsync();
        }
        
        public string[] GetGugun(string sido) {
            return base.Channel.GetGugun(sido);
        }
        
        public System.Threading.Tasks.Task<string[]> GetGugunAsync(string sido) {
            return base.Channel.GetGugunAsync(sido);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.tblPost[] GetAddress(string searchKeyword) {
            return base.Channel.GetAddress(searchKeyword);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.tblPost[]> GetAddressAsync(string searchKeyword) {
            return base.Channel.GetAddressAsync(searchKeyword);
        }
        
        public bool IsUserIdDuplicated(string userId) {
            return base.Channel.IsUserIdDuplicated(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsUserIdDuplicatedAsync(string userId) {
            return base.Channel.IsUserIdDuplicatedAsync(userId);
        }
        
        public bool IsNickNameDuplicated(string nickName) {
            return base.Channel.IsNickNameDuplicated(nickName);
        }
        
        public System.Threading.Tasks.Task<bool> IsNickNameDuplicatedAsync(string nickName) {
            return base.Channel.IsNickNameDuplicatedAsync(nickName);
        }
        
        public string MobileSendSMS(string mobile1, string mobile2, string mobile3) {
            return base.Channel.MobileSendSMS(mobile1, mobile2, mobile3);
        }
        
        public System.Threading.Tasks.Task<string> MobileSendSMSAsync(string mobile1, string mobile2, string mobile3) {
            return base.Channel.MobileSendSMSAsync(mobile1, mobile2, mobile3);
        }
        
        public bool CompanyExists(string ssno1, string ssno2, string ssno3) {
            return base.Channel.CompanyExists(ssno1, ssno2, ssno3);
        }
        
        public System.Threading.Tasks.Task<bool> CompanyExistsAsync(string ssno1, string ssno2, string ssno3) {
            return base.Channel.CompanyExistsAsync(ssno1, ssno2, ssno3);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthResult EmailAuth(int userNumber, string email, bool isMobile) {
            return base.Channel.EmailAuth(userNumber, email, isMobile);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthResult> EmailAuthAsync(int userNumber, string email, bool isMobile) {
            return base.Channel.EmailAuthAsync(userNumber, email, isMobile);
        }
        
        public Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthCompleteResult EmailAuthComplete(int userNumber, string email) {
            return base.Channel.EmailAuthComplete(userNumber, email);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db89.wowbill.Member.EmailAuthCompleteResult> EmailAuthCompleteAsync(int userNumber, string email) {
            return base.Channel.EmailAuthCompleteAsync(userNumber, email);
        }
        
        public void BillingServiceTest(string userId) {
            base.Channel.BillingServiceTest(userId);
        }
        
        public System.Threading.Tasks.Task BillingServiceTestAsync(string userId) {
            return base.Channel.BillingServiceTestAsync(userId);
        }
        
        public void EmailSendTest(string mailCode, string toName, string toEmail, string fromName, string fromEmail, string subject, string contents) {
            base.Channel.EmailSendTest(mailCode, toName, toEmail, fromName, fromEmail, subject, contents);
        }
        
        public System.Threading.Tasks.Task EmailSendTestAsync(string mailCode, string toName, string toEmail, string fromName, string fromEmail, string subject, string contents) {
            return base.Channel.EmailSendTestAsync(mailCode, toName, toEmail, fromName, fromEmail, subject, contents);
        }
    }
}
