//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.NewsMainService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsMainService.INewsMainService")]
    public interface INewsMainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainNewsstand", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainNewsstandResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_NEWSSTAND_SELECT_Result> GetNewsMainNewsstand();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainNewsstand", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainNewsstandResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_NEWSSTAND_SELECT_Result>> GetNewsMainNewsstandAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainOpinionList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainOpinionListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_OPINION_SELECT_Result> GetNewsMainOpinionList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainOpinionList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainOpinionListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_OPINION_SELECT_Result>> GetNewsMainOpinionListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainMarketIssueList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainMarketIssueListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_ISSUE_SELECT_Result> GetNewsMainMarketIssueList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainMarketIssueList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainMarketIssueListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_ISSUE_SELECT_Result>> GetNewsMainMarketIssueListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainEntSpoList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainEntSpoListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_ENT_SPO_SELECT_Result> GetNewsMainEntSpoList(string searchGubun, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainEntSpoList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainEntSpoListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_ENT_SPO_SELECT_Result>> GetNewsMainEntSpoListAsync(string searchGubun, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainVodList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainVodListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_VOD_SELECT_Result> GetNewsMainVodList(string searchGubun, System.Nullable<int> topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainVodList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainVodListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_VOD_SELECT_Result>> GetNewsMainVodListAsync(string searchGubun, System.Nullable<int> topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainCardList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainCardListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_CARD_SELECT_Result> GetNewsMainCardList(string searchGubun, System.Nullable<int> topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainCardList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainCardListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_CARD_SELECT_Result>> GetNewsMainCardListAsync(string searchGubun, System.Nullable<int> topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainSectionList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainSectionListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_SECTION_SELECT_Result> GetNewsMainSectionList(string searchGubun, System.Nullable<int> topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainSectionList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainSectionListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_SECTION_SELECT_Result>> GetNewsMainSectionListAsync(string searchGubun, System.Nullable<int> topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainYList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainYListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LIST_Y_SELECT_Result> GetNewsMainYList(string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainYList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainYListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LIST_Y_SELECT_Result>> GetNewsMainYListAsync(string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainMarketList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainMarketListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_SELECT_Result> GetNewsMainMarketList(string searchGubun, int topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainMarketList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainMarketListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_SELECT_Result>> GetNewsMainMarketListAsync(string searchGubun, int topN, string[] articleIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainLandList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainLandListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LAND_SELECT_Result> GetNewsMainLandList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsMainService/GetNewsMainLandList", ReplyAction="http://tempuri.org/INewsMainService/GetNewsMainLandListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LAND_SELECT_Result>> GetNewsMainLandListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsMainServiceChannel : Wow.Tv.FrontWeb.NewsMainService.INewsMainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsMainServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.NewsMainService.INewsMainService>, Wow.Tv.FrontWeb.NewsMainService.INewsMainService {
        
        public NewsMainServiceClient() {
        }
        
        public NewsMainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsMainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsMainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsMainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_NEWSSTAND_SELECT_Result> GetNewsMainNewsstand() {
            return base.Channel.GetNewsMainNewsstand();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_NEWSSTAND_SELECT_Result>> GetNewsMainNewsstandAsync() {
            return base.Channel.GetNewsMainNewsstandAsync();
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_OPINION_SELECT_Result> GetNewsMainOpinionList() {
            return base.Channel.GetNewsMainOpinionList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_OPINION_SELECT_Result>> GetNewsMainOpinionListAsync() {
            return base.Channel.GetNewsMainOpinionListAsync();
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_ISSUE_SELECT_Result> GetNewsMainMarketIssueList() {
            return base.Channel.GetNewsMainMarketIssueList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_ISSUE_SELECT_Result>> GetNewsMainMarketIssueListAsync() {
            return base.Channel.GetNewsMainMarketIssueListAsync();
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_ENT_SPO_SELECT_Result> GetNewsMainEntSpoList(string searchGubun, string[] articleIdList) {
            return base.Channel.GetNewsMainEntSpoList(searchGubun, articleIdList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_ENT_SPO_SELECT_Result>> GetNewsMainEntSpoListAsync(string searchGubun, string[] articleIdList) {
            return base.Channel.GetNewsMainEntSpoListAsync(searchGubun, articleIdList);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_VOD_SELECT_Result> GetNewsMainVodList(string searchGubun, System.Nullable<int> topN, string[] articleIdList) {
            return base.Channel.GetNewsMainVodList(searchGubun, topN, articleIdList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_VOD_SELECT_Result>> GetNewsMainVodListAsync(string searchGubun, System.Nullable<int> topN, string[] articleIdList) {
            return base.Channel.GetNewsMainVodListAsync(searchGubun, topN, articleIdList);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_CARD_SELECT_Result> GetNewsMainCardList(string searchGubun, System.Nullable<int> topN, string[] articleIdList) {
            return base.Channel.GetNewsMainCardList(searchGubun, topN, articleIdList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_CARD_SELECT_Result>> GetNewsMainCardListAsync(string searchGubun, System.Nullable<int> topN, string[] articleIdList) {
            return base.Channel.GetNewsMainCardListAsync(searchGubun, topN, articleIdList);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_SECTION_SELECT_Result> GetNewsMainSectionList(string searchGubun, System.Nullable<int> topN, string[] articleIdList) {
            return base.Channel.GetNewsMainSectionList(searchGubun, topN, articleIdList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_SECTION_SELECT_Result>> GetNewsMainSectionListAsync(string searchGubun, System.Nullable<int> topN, string[] articleIdList) {
            return base.Channel.GetNewsMainSectionListAsync(searchGubun, topN, articleIdList);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LIST_Y_SELECT_Result> GetNewsMainYList(string[] articleIdList) {
            return base.Channel.GetNewsMainYList(articleIdList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LIST_Y_SELECT_Result>> GetNewsMainYListAsync(string[] articleIdList) {
            return base.Channel.GetNewsMainYListAsync(articleIdList);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_SELECT_Result> GetNewsMainMarketList(string searchGubun, int topN, string[] articleIdList) {
            return base.Channel.GetNewsMainMarketList(searchGubun, topN, articleIdList);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_MARKET_SELECT_Result>> GetNewsMainMarketListAsync(string searchGubun, int topN, string[] articleIdList) {
            return base.Channel.GetNewsMainMarketListAsync(searchGubun, topN, articleIdList);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LAND_SELECT_Result> GetNewsMainLandList() {
            return base.Channel.GetNewsMainLandList();
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.Article.NUP_NEWS_MAIN_LAND_SELECT_Result>> GetNewsMainLandListAsync() {
            return base.Channel.GetNewsMainLandListAsync();
        }
    }
}
