//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wow.Tv.FrontWeb.MainManageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MainManageService.IMainManageService")]
    public interface IMainManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/SearchList", ReplyAction="http://tempuri.org/IMainManageService/SearchListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.MainManage.MainManageCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/SearchList", ReplyAction="http://tempuri.org/IMainManageService/SearchListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.MainManage.MainManageCondition condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/GetAt", ReplyAction="http://tempuri.org/IMainManageService/GetAtResponse")]
        Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE GetAt(int mainManageSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/GetAt", ReplyAction="http://tempuri.org/IMainManageService/GetAtResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE> GetAtAsync(int mainManageSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/Save", ReplyAction="http://tempuri.org/IMainManageService/SaveResponse")]
        int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/Save", ReplyAction="http://tempuri.org/IMainManageService/SaveResponse")]
        System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/Delete", ReplyAction="http://tempuri.org/IMainManageService/DeleteResponse")]
        void Delete(int mainManageSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/Delete", ReplyAction="http://tempuri.org/IMainManageService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int mainManageSeq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/UpDown", ReplyAction="http://tempuri.org/IMainManageService/UpDownResponse")]
        void UpDown(int mainManageSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/UpDown", ReplyAction="http://tempuri.org/IMainManageService/UpDownResponse")]
        System.Threading.Tasks.Task UpDownAsync(int mainManageSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/GetFrontList", ReplyAction="http://tempuri.org/IMainManageService/GetFrontListResponse")]
        Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE> GetFrontList(string mainTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainManageService/GetFrontList", ReplyAction="http://tempuri.org/IMainManageService/GetFrontListResponse")]
        System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE>> GetFrontListAsync(string mainTypeCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMainManageServiceChannel : Wow.Tv.FrontWeb.MainManageService.IMainManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainManageServiceClient : System.ServiceModel.ClientBase<Wow.Tv.FrontWeb.MainManageService.IMainManageService>, Wow.Tv.FrontWeb.MainManageService.IMainManageService {
        
        public MainManageServiceClient() {
        }
        
        public MainManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE> SearchList(Wow.Tv.Middle.Model.Db49.wowtv.MainManage.MainManageCondition condition) {
            return base.Channel.SearchList(condition);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE>> SearchListAsync(Wow.Tv.Middle.Model.Db49.wowtv.MainManage.MainManageCondition condition) {
            return base.Channel.SearchListAsync(condition);
        }
        
        public Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE GetAt(int mainManageSeq) {
            return base.Channel.GetAt(mainManageSeq);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE> GetAtAsync(int mainManageSeq) {
            return base.Channel.GetAtAsync(mainManageSeq);
        }
        
        public int Save(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.Save(model, loginUser);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE model, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.SaveAsync(model, loginUser);
        }
        
        public void Delete(int mainManageSeq) {
            base.Channel.Delete(mainManageSeq);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int mainManageSeq) {
            return base.Channel.DeleteAsync(mainManageSeq);
        }
        
        public void UpDown(int mainManageSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            base.Channel.UpDown(mainManageSeq, isUp, loginUser);
        }
        
        public System.Threading.Tasks.Task UpDownAsync(int mainManageSeq, bool isUp, Wow.Tv.Middle.Model.Common.LoginUser loginUser) {
            return base.Channel.UpDownAsync(mainManageSeq, isUp, loginUser);
        }
        
        public Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE> GetFrontList(string mainTypeCode) {
            return base.Channel.GetFrontList(mainTypeCode);
        }
        
        public System.Threading.Tasks.Task<Wow.Tv.Middle.Model.Common.ListModel<Wow.Tv.Middle.Model.Db49.wowtv.NTB_MAIN_MANAGE>> GetFrontListAsync(string mainTypeCode) {
            return base.Channel.GetFrontListAsync(mainTypeCode);
        }
    }
}
